export type GameCategory = "Action" | "Arcade" | "Puzzle" | "Runner" | "Sports";

export interface GameCatalogMetadata {
  creatorId: string;
  creatorName: string;
  creatorLabel: string;
  category: GameCategory;
}

export const GAME_CATALOG_METADATA: Record<string, GameCatalogMetadata> = {
  "pulse-lock": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "color-clash": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Puzzle",
  },
  "stack-shift": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "memory-grid": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Puzzle",
  },
  "meteor-dodge": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "subway-surfers": {
    creatorId: "sybo",
    creatorName: "SYBO",
    creatorLabel: "BY SYBO · TIP TAP INTEGRATION",
    category: "Runner",
  },
  "dino-runner": {
    creatorId: "chrome-ux",
    creatorName: "Chrome UX",
    creatorLabel: "BY CHROME UX · TIP TAP INTEGRATION",
    category: "Runner",
  },
  arithmetica: {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Puzzle",
  },
  "67-game": {
    creatorId: "stupidella",
    creatorName: "Stupidella",
    creatorLabel: "BY STUPIDELLA · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "archery-king": {
    creatorId: "code-this-lab",
    creatorName: "Code This Lab",
    creatorLabel: "BY CODE THIS LAB · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "smash-room": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER LTD · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "temple-run-2-frozen-shadows": {
    creatorId: "imangi",
    creatorName: "Imangi Studios",
    creatorLabel: "BY IMANGI STUDIOS · LOCAL SOURCE MIRROR",
    category: "Runner",
  },
  "stickman-fury": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER LTD · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  plonky: {
    creatorId: "gametornado",
    creatorName: "GameTornado",
    creatorLabel: "BY GAMETORNADO · LOCAL SOURCE MIRROR",
    category: "Arcade",
  },
  "fruit-ninja": {
    creatorId: "storms",
    creatorName: "Storms",
    creatorLabel: "BY STORMS · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "count-control-legends": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Runner",
  },
  "johnny-trigger-sniper": {
    creatorId: "saygames",
    creatorName: "SayGames",
    creatorLabel: "BY SAYGAMES · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "rocket-soccer-derby": {
    creatorId: "destruction-crew",
    creatorName: "Destruction Crew",
    creatorLabel: "BY DESTRUCTION CREW · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "dig-out-of-prison": {
    creatorId: "incredi-games",
    creatorName: "Incredi.Games",
    creatorLabel: "BY INCREDI.GAMES · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "kitty-loves-birds-2": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Runner",
  },
  "theft-city": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Action",
  },
  "city-cab-rush": {
    creatorId: "storerider",
    creatorName: "StoreRider",
    creatorLabel: "BY STORERIDER · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "supercar-legends": {
    creatorId: "jungle-tavern",
    creatorName: "Jungle Tavern",
    creatorLabel: "BY JUNGLE TAVERN · TIP TAP INTEGRATION",
    category: "Runner",
  },
  "ping-pong-go": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER · TIP TAP INTEGRATION",
    category: "Sports",
  },
  "tic-tac-toe": {
    creatorId: "cocos-dev",
    creatorName: "Cocos Creator",
    creatorLabel: "BY COCOS CREATOR · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "go-battle-2": {
    creatorId: "poki-mirror",
    creatorName: "Go Battle 2",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "stickman-battle": {
    creatorId: "poki-mirror",
    creatorName: "Stickman Battle",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "retro-bowl": {
    creatorId: "poki-mirror",
    creatorName: "Retro Bowl",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "domino": { creatorId: "domino", creatorName: "Domino", creatorLabel: "BY DOMINO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "foosball": { creatorId: "foosball", creatorName: "Foosball", creatorLabel: "BY FOOSBALL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ludo-hero": { creatorId: "ludo-hero", creatorName: "Ludo Hero", creatorLabel: "BY LUDO HERO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moto-x3m": { creatorId: "moto-x3m", creatorName: "Moto X3M", creatorLabel: "BY MOTO X3M · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubble-storm": { creatorId: "bubble-storm", creatorName: "Bubble Storm", creatorLabel: "BY BUBBLE STORM · LOCAL SOURCE MIRROR", category: "Arcade" },
  "spider-solitaire": { creatorId: "chrome-and-opera", creatorName: "Chrome and Opera", creatorLabel: "BY CHROME AND OPERA · LOCAL SOURCE MIRROR", category: "Arcade" },
  "master-checkers": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "four-in-a-row": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "monkey-mart": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "eggy-car": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiny-fishing": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "beauty-salon": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fashion-fix-studio": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "phone-case-diy": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "clean-house": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stunt-bike-extreme": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "idle-lumber-inc": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "my-perfect-hotel": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snapstyle-dress-up": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brain-test-tricky-puzzles": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "little-farm-world": { creatorId: "little-farm-world", creatorName: "Little Farm World", creatorLabel: "BY LITTLE FARM WORLD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moms-diary-cooking-games": { creatorId: "mom-s-diary-cooking-games", creatorName: "Mom's Diary Cooking Games", creatorLabel: "BY MOM'S DIARY COOKING GAMES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "scary-teacher-hide-seek-games": { creatorId: "scary-teacher-hide-seek-games", creatorName: "Scary Teacher Hide & Seek Games", creatorLabel: "BY SCARY TEACHER HIDE & SEEK GAMES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "demolition-simulator": { creatorId: "demolition-simulator", creatorName: "Demolition Simulator", creatorLabel: "BY DEMOLITION SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "family-sort": { creatorId: "family-sort", creatorName: "Family Sort", creatorLabel: "BY FAMILY SORT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kick-the-buddy": { creatorId: "kick-the-buddy", creatorName: "Kick The Buddy", creatorLabel: "BY KICK THE BUDDY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "slime-keyboard-escape": { creatorId: "slime-keyboard-escape", creatorName: "Slime Keyboard Escape", creatorLabel: "BY SLIME KEYBOARD ESCAPE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dragon-the-dragon": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pet-mahjong-3d": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "petnest-io": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "travel-merge": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "build-your-island": { creatorId: "build-your-island", creatorName: "Build Your Island", creatorLabel: "BY BUILD YOUR ISLAND · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sandbox-of-elements": { creatorId: "sandbox-of-elements", creatorName: "Sandbox of Elements", creatorLabel: "BY SANDBOX OF ELEMENTS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "crowd-rush": { creatorId: "crowd-rush", creatorName: "Crowd Rush", creatorLabel: "BY CROWD RUSH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "harvest-loop": { creatorId: "harvest-loop", creatorName: "Harvest Loop", creatorLabel: "BY HARVEST LOOP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiny-game-shop-tycoon": { creatorId: "tiny-game-shop-tycoon", creatorName: "Tiny Game Shop Tycoon", creatorLabel: "BY TINY GAME SHOP TYCOON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "undead-slayer": { creatorId: "undead-slayer", creatorName: "Undead Slayer", creatorLabel: "BY UNDEAD SLAYER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "knife-merge": { creatorId: "knife-merge", creatorName: "Knife Merge", creatorLabel: "BY KNIFE MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "family-life-simulator": { creatorId: "family-life-simulator", creatorName: "Family Life Simulator", creatorLabel: "BY FAMILY LIFE SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dummies-fight": { creatorId: "dummies-fight", creatorName: "Dummies Fight", creatorLabel: "BY DUMMIES FIGHT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "perfect-shape": { creatorId: "perfect-shape", creatorName: "Perfect Shape", creatorLabel: "BY PERFECT SHAPE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "flip-pounce": { creatorId: "flip-pounce", creatorName: "Flip Pounce", creatorLabel: "BY FLIP POUNCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "goalheads-io": { creatorId: "goalheads-io", creatorName: "GoalHeads.io", creatorLabel: "BY GOALHEADS.IO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "goods-master": { creatorId: "goods-master", creatorName: "Goods Master", creatorLabel: "BY GOODS MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "20f8": { creatorId: "20f8", creatorName: "20f8", creatorLabel: "BY 20F8 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fashion-dress-up-star": { creatorId: "fashion-dress-up-star", creatorName: "Fashion Dress Up Star", creatorLabel: "BY FASHION DRESS UP STAR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dino-simulator": { creatorId: "dino-simulator", creatorName: "Dino Simulator", creatorLabel: "BY DINO SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubbleshooter-x-basketball-3d": { creatorId: "bubbleshooter-x-basketball-3d", creatorName: "Bubbleshooter x Basketball 3D", creatorLabel: "BY BUBBLESHOOTER X BASKETBALL 3D · LOCAL SOURCE MIRROR", category: "Arcade" },
  "boomy-world": { creatorId: "boomy-world", creatorName: "Boomy World", creatorLabel: "BY BOOMY WORLD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "chick-flix": { creatorId: "chick-flix", creatorName: "Chick Flix", creatorLabel: "BY CHICK FLIX · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ball-guys": { creatorId: "ball-guys", creatorName: "Ball Guys", creatorLabel: "BY BALL GUYS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "color-shapes": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "paperio-2": { creatorId: "merci-michel-preproduction", creatorName: "Merci-Michel Preproduction", creatorLabel: "BY MERCI-MICHEL PREPRODUCTION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snow-yeet": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "robo-cleaner-simulator": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "noob-archer-2": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "carnado-boat-racing": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "super-dress": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "block-for-blood": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dress-up-party": { creatorId: "dress-up-party", creatorName: "Dress Up Party", creatorLabel: "BY DRESS UP PARTY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cuboy-adventure": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ragdoll-chaos": { creatorId: "ragdoll-chaos", creatorName: "Ragdoll Chaos", creatorLabel: "BY RAGDOLL CHAOS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "critter-chaos": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "happy-tidy-time": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "soccer-league": { creatorId: "soccer-league", creatorName: "Soccer League", creatorLabel: "BY SOCCER LEAGUE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moto-trap": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiny-baker-ocean-jelly-cake": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "robo-cleaner-simulator": { creatorId: "robo-cleaner-simulator", creatorName: "Robo Cleaner Simulator", creatorLabel: "BY ROBO CLEANER SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "escape-from-scary-teacher": { creatorId: "escape-from-scary-teacher", creatorName: "Escape from Scary Teacher", creatorLabel: "BY ESCAPE FROM SCARY TEACHER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "noob-archer-2": { creatorId: "noob-archer-2", creatorName: "Noob Archer 2", creatorLabel: "BY NOOB ARCHER 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dogs-life": { creatorId: "dog-s-life", creatorName: "Dog's Life", creatorLabel: "BY DOG'S LIFE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "planet-merge": { creatorId: "planet-merge", creatorName: "Planet Merge", creatorLabel: "BY PLANET MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stickman-merge": { creatorId: "stickman-merge", creatorName: "Stickman Merge", creatorLabel: "BY STICKMAN MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "jelly-well": { creatorId: "jelly-well", creatorName: "Jelly Well", creatorLabel: "BY JELLY WELL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "backrooms-recovery": { creatorId: "backrooms-recovery", creatorName: "Backrooms Recovery", creatorLabel: "BY BACKROOMS RECOVERY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "upgrade-the-cars": { creatorId: "upgrade-the-cars", creatorName: "Upgrade the CARS", creatorLabel: "BY UPGRADE THE CARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "mad-skills-rallycross": { creatorId: "mad-skills-rallycross", creatorName: "Mad Skills Rallycross", creatorLabel: "BY MAD SKILLS RALLYCROSS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pull-a-sword": { creatorId: "pull-a-sword", creatorName: "Pull a Sword", creatorLabel: "BY PULL A SWORD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "trapped-in-the-dollhouse": { creatorId: "trapped-in-the-dollhouse", creatorName: "Trapped in the Dollhouse", creatorLabel: "BY TRAPPED IN THE DOLLHOUSE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tds-tower-destiny-survive": { creatorId: "tower-destiny-survive", creatorName: "Tower Destiny Survive", creatorLabel: "BY TOWER DESTINY SURVIVE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fight-and-loot": { creatorId: "fight-and-loot", creatorName: "Fight and Loot", creatorLabel: "BY FIGHT AND LOOT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sea-of-sharks": { creatorId: "sea-of-sharks", creatorName: "Sea of Sharks", creatorLabel: "BY SEA OF SHARKS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cuboy-adventure": { creatorId: "cuboy-adventure", creatorName: "Cuboy Adventure", creatorLabel: "BY CUBOY ADVENTURE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "clash-of-cards": { creatorId: "clash-of-cards", creatorName: "Clash of Cards", creatorLabel: "BY CLASH OF CARDS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "oozys-lab": { creatorId: "oozy-s-lab", creatorName: "Oozy's Lab", creatorLabel: "BY OOZY'S LAB · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dan-the-man": { creatorId: "dan-the-man", creatorName: "Dan The Man", creatorLabel: "BY DAN THE MAN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "samurai-sam": { creatorId: "samurai-sam", creatorName: "Samurai Sam", creatorLabel: "BY SAMURAI SAM · LOCAL SOURCE MIRROR", category: "Arcade" },
  "punch-master": { creatorId: "punch-master", creatorName: "Punch Master", creatorLabel: "BY PUNCH MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "soccer-5": { creatorId: "soccer-5", creatorName: "Soccer 5", creatorLabel: "BY SOCCER 5 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "hero-vs-criminal": { creatorId: "hero-vs-criminal", creatorName: "Hero VS Criminal", creatorLabel: "BY HERO VS CRIMINAL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brain-test-5": { creatorId: "brain-test-5", creatorName: "Brain Test 5", creatorLabel: "BY BRAIN TEST 5 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "numbers-match": { creatorId: "numbers-match-2448", creatorName: "Numbers Match 2448", creatorLabel: "BY NUMBERS MATCH 2448 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "superweird": { creatorId: "superweird", creatorName: "SuperWEIRD", creatorLabel: "BY SUPERWEIRD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moto-trap": { creatorId: "moto-trap", creatorName: "Moto Trap", creatorLabel: "BY MOTO TRAP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "car-circle": { creatorId: "car-circle", creatorName: "Car Circle", creatorLabel: "BY CAR CIRCLE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ball-vs-block": { creatorId: "ball-vs-block", creatorName: "Ball vs Block", creatorLabel: "BY BALL VS BLOCK · LOCAL SOURCE MIRROR", category: "Arcade" },
  "home-builder-clicker": { creatorId: "home-builder-clicker", creatorName: "Home Builder Clicker", creatorLabel: "BY HOME BUILDER CLICKER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sea-catcher": { creatorId: "sea-catcher", creatorName: "Sea Catcher", creatorLabel: "BY SEA CATCHER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kitten-out": { creatorId: "kitten-out", creatorName: "Kitten Out", creatorLabel: "BY KITTEN OUT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "marina-club-rush": { creatorId: "marina-club-rush", creatorName: "Marina Club Rush", creatorLabel: "BY MARINA CLUB RUSH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "airplane-manager": { creatorId: "airplane-manager", creatorName: "Airplane Manager", creatorLabel: "BY AIRPLANE MANAGER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "gunforce": { creatorId: "gunforce", creatorName: "GunForce", creatorLabel: "BY GUNFORCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "spacebar-clicker": { creatorId: "spacebar-clicker", creatorName: "Spacebar Clicker", creatorLabel: "BY SPACEBAR CLICKER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "veggie-merge": { creatorId: "veggie-merge", creatorName: "Veggie Merge", creatorLabel: "BY VEGGIE MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "a-small-world-cup-2": { creatorId: "a-small-world-cup-2", creatorName: "A Small World Cup 2", creatorLabel: "BY A SMALL WORLD CUP 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tens": { creatorId: "tens", creatorName: "Tens!", creatorLabel: "BY TENS! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "lafufu-blind-box-dress-up": { creatorId: "lafufu-blind-box-dress-up", creatorName: "Lafufu Blind Box Dress Up", creatorLabel: "BY LAFUFU BLIND BOX DRESS UP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "find-it": { creatorId: "find-it", creatorName: "Find it!", creatorLabel: "BY FIND IT! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sushi-situation": { creatorId: "sushi-situation", creatorName: "Sushi Situation", creatorLabel: "BY SUSHI SITUATION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "draft-wars": { creatorId: "draft-wars", creatorName: "Draft Wars", creatorLabel: "BY DRAFT WARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "annoying-teacher-punch-game": { creatorId: "annoying-teacher-punch-game", creatorName: "Annoying Teacher Punch Game", creatorLabel: "BY ANNOYING TEACHER PUNCH GAME · LOCAL SOURCE MIRROR", category: "Arcade" },
  "battle-blast": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "catch-a-pet": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "hide-and-paint": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "make-brainrots-online": { creatorId: "make-brainrots-online", creatorName: "Make Brainrots Online", creatorLabel: "BY MAKE BRAINROTS ONLINE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "monkey-tag-io": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stickers-merge": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiger-tank-2": { creatorId: "layaair-engine", creatorName: "LayaAir Engine", creatorLabel: "BY LAYAAIR ENGINE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "duck-merge": { creatorId: "duck-merge", creatorName: "Duck Merge", creatorLabel: "BY DUCK MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blumgi-splash": { creatorId: "blumgi-splash", creatorName: "Blumgi Splash", creatorLabel: "BY BLUMGI SPLASH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "school-cleaning": { creatorId: "school-cleaning", creatorName: "School Cleaning", creatorLabel: "BY SCHOOL CLEANING · LOCAL SOURCE MIRROR", category: "Arcade" },
  "talking-tom-gold-run": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cozyville-find-hidden-objects": { creatorId: "cozyville-find-hidden-objects", creatorName: "Cozyville - Find Hidden Objects", creatorLabel: "BY COZYVILLE - FIND HIDDEN OBJECTS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stunt-protocol-two-players": { creatorId: "stunt-protocol", creatorName: "Stunt Protocol", creatorLabel: "BY STUNT PROTOCOL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "guns-guns-guns": { creatorId: "guns-guns-guns", creatorName: "Guns Guns Guns", creatorLabel: "BY GUNS GUNS GUNS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "world-of-yarn": { creatorId: "world-of-yarn", creatorName: "World of Yarn", creatorLabel: "BY WORLD OF YARN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bunny-miner": { creatorId: "bunny-miner", creatorName: "Bunny Miner", creatorLabel: "BY BUNNY MINER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "goal-gang": { creatorId: "goal-gang", creatorName: "Goal Gang", creatorLabel: "BY GOAL GANG · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubble-tower": { creatorId: "bubble-tower", creatorName: "Bubble Tower", creatorLabel: "BY BUBBLE TOWER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snacky-snake": { creatorId: "snacky-snake", creatorName: "Snacky Snake", creatorLabel: "BY SNACKY SNAKE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "zombit": { creatorId: "zombit", creatorName: "Zombit", creatorLabel: "BY ZOMBIT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "wheel-master": { creatorId: "wheel-master", creatorName: "Wheel Master", creatorLabel: "BY WHEEL MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "satisbox-builder": { creatorId: "satisbox-builder", creatorName: "Satisbox Builder", creatorLabel: "BY SATISBOX BUILDER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "carnado-bike-stunt": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blast-buddies": { creatorId: "blast-buddies", creatorName: "Blast Buddies", creatorLabel: "BY BLAST BUDDIES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "count-war": { creatorId: "count-war", creatorName: "Count War", creatorLabel: "BY COUNT WAR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "lips-diy-master": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "going-up-rooftop": { creatorId: "going-up-rooftop", creatorName: "Going Up Rooftop", creatorLabel: "BY GOING UP ROOFTOP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "lips-diy-master": { creatorId: "lips-diy-master", creatorName: "Lips Diy Master", creatorLabel: "BY LIPS DIY MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "keyboard-warrior": { creatorId: "keyboard-warrior", creatorName: "Keyboard Warrior", creatorLabel: "BY KEYBOARD WARRIOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "adventure-miner": { creatorId: "adventure-miner", creatorName: "Adventure Miner", creatorLabel: "BY ADVENTURE MINER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dino-fighter": { creatorId: "dino-fighter", creatorName: "Dino Fighter", creatorLabel: "BY DINO FIGHTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cleanup-crew": { creatorId: "cleanup-crew", creatorName: "Cleanup Crew", creatorLabel: "BY CLEANUP CREW · LOCAL SOURCE MIRROR", category: "Arcade" },
  "basketball-real": { creatorId: "basketball-real", creatorName: "Basketball REAL", creatorLabel: "BY BASKETBALL REAL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "crazy-merge": { creatorId: "crazy-merge", creatorName: "Crazy Merge", creatorLabel: "BY CRAZY MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "jelly-sokoban": { creatorId: "jelly-sokoban", creatorName: "Jelly Sokoban", creatorLabel: "BY JELLY SOKOBAN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "soccer-skills-2-world-cup": { creatorId: "soccer-skills-2-world-cup", creatorName: "Soccer Skills 2 World Cup", creatorLabel: "BY SOCCER SKILLS 2 WORLD CUP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kpop-concert-dress-up": { creatorId: "kpop-concert-dress-up", creatorName: "KPop Concert Dress Up", creatorLabel: "BY KPOP CONCERT DRESS UP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "drift-hunters": { creatorId: "drift-hunters", creatorName: "Drift Hunters", creatorLabel: "BY DRIFT HUNTERS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "knockout-penguins": { creatorId: "knockout-penguins", creatorName: "Knockout Penguins", creatorLabel: "BY KNOCKOUT PENGUINS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "decor-life": { creatorId: "decor-life", creatorName: "Decor Life", creatorLabel: "BY DECOR LIFE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "janes-fashion-studio": { creatorId: "jane-s-fashion-studio", creatorName: "Jane's Fashion Studio", creatorLabel: "BY JANE'S FASHION STUDIO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "real-city-bikes": { creatorId: "real-city-bikes", creatorName: "Real City Bikes", creatorLabel: "BY REAL CITY BIKES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sort-the-court": { creatorId: "sort-the-court", creatorName: "Sort the Court!", creatorLabel: "BY SORT THE COURT! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "skill-knight": { creatorId: "skill-knight", creatorName: "Skill Knight", creatorLabel: "BY SKILL KNIGHT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "jelly-fruit-merge": { creatorId: "jelly-fruit-merge", creatorName: "Jelly Fruit Merge", creatorLabel: "BY JELLY FRUIT MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "wreck-the-robot": { creatorId: "wreck-the-robot", creatorName: "Wreck The Robot", creatorLabel: "BY WRECK THE ROBOT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "freaky-clown-town-mystery": { creatorId: "freaky-clown-town-mystery", creatorName: "Freaky Clown Town Mystery", creatorLabel: "BY FREAKY CLOWN TOWN MYSTERY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "magic-battleground": { creatorId: "magic-battleground", creatorName: "Magic Battleground", creatorLabel: "BY MAGIC BATTLEGROUND · LOCAL SOURCE MIRROR", category: "Arcade" },
  "free-skate": { creatorId: "free-skate", creatorName: "Free Skate", creatorLabel: "BY FREE SKATE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "alien-raid-monster-evolution": { creatorId: "alien-raid-monster-evolution", creatorName: "Alien Raid Monster Evolution", creatorLabel: "BY ALIEN RAID MONSTER EVOLUTION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tuning-car-racing": { creatorId: "tuning-car-racing", creatorName: "Tuning Car Racing", creatorLabel: "BY TUNING CAR RACING · LOCAL SOURCE MIRROR", category: "Arcade" },
  "metamon": { creatorId: "metamon", creatorName: "Metamon", creatorLabel: "BY METAMON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "crazy-race": { creatorId: "crazy-race", creatorName: "Crazy Race", creatorLabel: "BY CRAZY RACE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "diva-makeup-studio": { creatorId: "diva-makeup-studio", creatorName: "Diva Makeup Studio", creatorLabel: "BY DIVA MAKEUP STUDIO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "flat-baseball": { creatorId: "flat-baseball", creatorName: "Flat Baseball", creatorLabel: "BY FLAT BASEBALL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cat-simulator": { creatorId: "cat-simulator", creatorName: "Cat Simulator", creatorLabel: "BY CAT SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fashion-legends": { creatorId: "fashion-legends", creatorName: "Fashion Legends", creatorLabel: "BY FASHION LEGENDS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "mine-and-dig": { creatorId: "mine-and-dig", creatorName: "Mine and Dig", creatorLabel: "BY MINE AND DIG · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tank-stars": { creatorId: "tank-stars", creatorName: "Tank Stars", creatorLabel: "BY TANK STARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "4th-and-goal-2026": { creatorId: "4th-and-goal-2026", creatorName: "4th and Goal 2026", creatorLabel: "BY 4TH AND GOAL 2026 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "punchy-guy": { creatorId: "punchy-guy", creatorName: "Punchy Guy", creatorLabel: "BY PUNCHY GUY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "you-monster": { creatorId: "you-monster", creatorName: "You Monster!", creatorLabel: "BY YOU MONSTER! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "push-titans": { creatorId: "push-titans", creatorName: "Push Titans", creatorLabel: "BY PUSH TITANS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "neon-challenge-legends": { creatorId: "neon-challenge-legends", creatorName: "Neon Challenge Legends", creatorLabel: "BY NEON CHALLENGE LEGENDS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ludo-king": { creatorId: "ludo-king", creatorName: "Ludo King", creatorLabel: "BY LUDO KING · LOCAL SOURCE MIRROR", category: "Arcade" },
  "idle-spinner-factory-builder": { creatorId: "idle-spinner-factory-builder", creatorName: "Idle Spinner Factory Builder", creatorLabel: "BY IDLE SPINNER FACTORY BUILDER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "gas-station": { creatorId: "gas-station", creatorName: "Gas Station", creatorLabel: "BY GAS STATION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "grass-knight": { creatorId: "grass-knight", creatorName: "Grass Knight", creatorLabel: "BY GRASS KNIGHT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "slime-dunk": { creatorId: "slime-dunk", creatorName: "Slime Dunk!", creatorLabel: "BY SLIME DUNK! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "the-superhero-league-2": { creatorId: "the-superhero-league-2", creatorName: "The Superhero League 2", creatorLabel: "BY THE SUPERHERO LEAGUE 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sword-road": { creatorId: "sword-road", creatorName: "Sword Road", creatorLabel: "BY SWORD ROAD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "carrom-multiplayer": { creatorId: "carrom-multiplayer", creatorName: "Carrom Multiplayer", creatorLabel: "BY CARROM MULTIPLAYER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "turnament": { creatorId: "turnament", creatorName: "Turnament", creatorLabel: "BY TURNAMENT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "papa-louie-3": { creatorId: "papa-louie-3", creatorName: "Papa Louie 3", creatorLabel: "BY PAPA LOUIE 3 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "mirror-image": { creatorId: "mirror-image", creatorName: "Mirror Image", creatorLabel: "BY MIRROR IMAGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bos-bedroom": { creatorId: "bo-s-bedroom", creatorName: "Bo's Bedroom", creatorLabel: "BY BO'S BEDROOM · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubble-heroes": { creatorId: "bubble-heroes", creatorName: "Bubble Heroes", creatorLabel: "BY BUBBLE HEROES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "racing-rampage": { creatorId: "racing-rampage", creatorName: "Racing Rampage", creatorLabel: "BY RACING RAMPAGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snek-left": { creatorId: "snek-left", creatorName: "Snek Left", creatorLabel: "BY SNEK LEFT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snow-riders": { creatorId: "snow-riders", creatorName: "Snow Riders", creatorLabel: "BY SNOW RIDERS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "papa-louie-2": { creatorId: "papa-louie-2", creatorName: "Papa Louie 2", creatorLabel: "BY PAPA LOUIE 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "whip-flip": { creatorId: "whip-flip", creatorName: "Whip & Flip", creatorLabel: "BY WHIP & FLIP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "human-bullet-gun": { creatorId: "human-bullet-gun", creatorName: "Human Bullet Gun", creatorLabel: "BY HUMAN BULLET GUN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "graveyard-shift": { creatorId: "graveyard-shift", creatorName: "Graveyard Shift", creatorLabel: "BY GRAVEYARD SHIFT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "speed-stars": { creatorId: "speed-stars", creatorName: "Speed Stars", creatorLabel: "BY SPEED STARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brain-test-special": { creatorId: "brain-test-special", creatorName: "Brain Test Special", creatorLabel: "BY BRAIN TEST SPECIAL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cat-bird": { creatorId: "cat-bird", creatorName: "Cat Bird", creatorLabel: "BY CAT BIRD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pizza-planet": { creatorId: "pizza-planet", creatorName: "Pizza Planet", creatorLabel: "BY PIZZA PLANET · LOCAL SOURCE MIRROR", category: "Arcade" },
  "eggsplosion": { creatorId: "eggsplosion", creatorName: "Eggsplosion", creatorLabel: "BY EGGSPLOSION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "planet-destruction": { creatorId: "planet-destruction", creatorName: "Planet Destruction", creatorLabel: "BY PLANET DESTRUCTION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tear-blocks-down": { creatorId: "tear-blocks-down", creatorName: "Tear Blocks Down", creatorLabel: "BY TEAR BLOCKS DOWN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "little-tricky-prankster": { creatorId: "little-tricky-prankster", creatorName: "Little Tricky Prankster", creatorLabel: "BY LITTLE TRICKY PRANKSTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "no-pain-no-gain": { creatorId: "no-pain-no-gain", creatorName: "No Pain No Gain", creatorLabel: "BY NO PAIN NO GAIN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cube-builder": { creatorId: "cube-builder", creatorName: "Cube Builder", creatorLabel: "BY CUBE BUILDER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "elf-backpack": { creatorId: "elf-backpack", creatorName: "Elf Backpack", creatorLabel: "BY ELF BACKPACK · LOCAL SOURCE MIRROR", category: "Arcade" },
  "wonder-high-dressup": { creatorId: "wonder-high-dress-up", creatorName: "Wonder High Dress-Up", creatorLabel: "BY WONDER HIGH DRESS-UP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pizza-day": { creatorId: "pizza-day", creatorName: "Pizza Day", creatorLabel: "BY PIZZA DAY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "obby-roads": { creatorId: "obby-roads", creatorName: "Obby Roads", creatorLabel: "BY OBBY ROADS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bacon-survivor": { creatorId: "bacon-survivor", creatorName: "Bacon Survivor", creatorLabel: "BY BACON SURVIVOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "hill-climb-racing-lite": { creatorId: "hill-climb-racing-lite", creatorName: "Hill Climb Racing Lite", creatorLabel: "BY HILL CLIMB RACING LITE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ludo-online": { creatorId: "ludo-online", creatorName: "Ludo Online", creatorLabel: "BY LUDO ONLINE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blumgi-bounce": { creatorId: "blumgi-bounce", creatorName: "Blumgi Bounce", creatorLabel: "BY BLUMGI BOUNCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ragdoll-drop": { creatorId: "ragdoll-drop", creatorName: "Ragdoll Drop", creatorLabel: "BY RAGDOLL DROP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kates-cooking-party": { creatorId: "kate-s-cooking-party", creatorName: "Kate's Cooking Party", creatorLabel: "BY KATE'S COOKING PARTY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dino-quake": { creatorId: "dino-quake", creatorName: "Dino Quake", creatorLabel: "BY DINO QUAKE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "beardie-craft-survival": { creatorId: "beardie-craft-survival", creatorName: "Beardie Craft Survival", creatorLabel: "BY BEARDIE CRAFT SURVIVAL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pro-shooter": { creatorId: "pro-shooter", creatorName: "Pro Shooter", creatorLabel: "BY PRO SHOOTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "my-city-horse-stable": { creatorId: "my-city-horse-stable", creatorName: "My City Horse Stable", creatorLabel: "BY MY CITY HORSE STABLE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "party-time": { creatorId: "party-time", creatorName: "Party Time", creatorLabel: "BY PARTY TIME · LOCAL SOURCE MIRROR", category: "Arcade" },
  "world-of-screw": { creatorId: "world-of-screw", creatorName: "World of Screw", creatorLabel: "BY WORLD OF SCREW · LOCAL SOURCE MIRROR", category: "Arcade" },
  "royal-flush-merge": { creatorId: "royal-flush-merge", creatorName: "Royal Flush Merge", creatorLabel: "BY ROYAL FLUSH MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "monster-max": { creatorId: "monster-max", creatorName: "Monster Max", creatorLabel: "BY MONSTER MAX · LOCAL SOURCE MIRROR", category: "Arcade" },
  "life-choices-2-life-simulator": { creatorId: "life-choices-2-life-simulator", creatorName: "Life Choices 2: Life Simulator", creatorLabel: "BY LIFE CHOICES 2: LIFE SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "nail-salon": { creatorId: "nail-salon", creatorName: "Nail Salon", creatorLabel: "BY NAIL SALON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "subway-surfers-blast": { creatorId: "subway-surfers-blast", creatorName: "Subway Surfers Blast", creatorLabel: "BY SUBWAY SURFERS BLAST · LOCAL SOURCE MIRROR", category: "Arcade" },
  "subway-surfers-match": { creatorId: "subway-surfers-match", creatorName: "Subway Surfers Match", creatorLabel: "BY SUBWAY SURFERS MATCH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "scary-teacher-playtime-adventure": { creatorId: "scary-teacher-playtime-adventure", creatorName: "Scary Teacher PlayTime Adventure", creatorLabel: "BY SCARY TEACHER PLAYTIME ADVENTURE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sky-race": { creatorId: "sky-race", creatorName: "Sky Race", creatorLabel: "BY SKY RACE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snake-vs-human": { creatorId: "snake-vs-human", creatorName: "Snake Vs Human", creatorLabel: "BY SNAKE VS HUMAN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "thung-wars": { creatorId: "thung-wars", creatorName: "Thung Wars", creatorLabel: "BY THUNG WARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "grass-cutter": { creatorId: "grass-cutter", creatorName: "Grass Cutter", creatorLabel: "BY GRASS CUTTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "color-merge-lines": { creatorId: "color-merge-lines", creatorName: "Color Merge Lines", creatorLabel: "BY COLOR MERGE LINES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "roller": { creatorId: "roller", creatorName: "Roller", creatorLabel: "BY ROLLER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stickman-maze-run": { creatorId: "stickman-maze-run", creatorName: "Stickman Maze Run", creatorLabel: "BY STICKMAN MAZE RUN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dwerg": { creatorId: "dwerg", creatorName: "Dwerg", creatorLabel: "BY DWERG · LOCAL SOURCE MIRROR", category: "Arcade" },
  "hockey-taka": { creatorId: "hockey-taka", creatorName: "Hockey Taka", creatorLabel: "BY HOCKEY TAKA · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pocket-car-city": { creatorId: "pocket-car-city", creatorName: "Pocket Car City!", creatorLabel: "BY POCKET CAR CITY! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "the-third-piglets-tower": { creatorId: "the-third-piglet-s-tower", creatorName: "The Third Piglet's Tower", creatorLabel: "BY THE THIRD PIGLET'S TOWER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "capitalist-bus-driver": { creatorId: "capitalist-bus-driver", creatorName: "Capitalist Bus Driver", creatorLabel: "BY CAPITALIST BUS DRIVER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stupidella-horror-2": { creatorId: "stupidella-horror-2", creatorName: "Stupidella Horror 2", creatorLabel: "BY STUPIDELLA HORROR 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "merge-monster-battles": { creatorId: "merge-monster-battles", creatorName: "Merge Monster Battles", creatorLabel: "BY MERGE MONSTER BATTLES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brainrot-merge": { creatorId: "brainrot-merge", creatorName: "Brainrot Merge", creatorLabel: "BY BRAINROT MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "critters-quest": { creatorId: "critters-quest", creatorName: "Critters Quest", creatorLabel: "BY CRITTERS QUEST · LOCAL SOURCE MIRROR", category: "Arcade" },
  "the-real-juggle": { creatorId: "the-real-juggle", creatorName: "The Real Juggle", creatorLabel: "BY THE REAL JUGGLE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "evolution-game": { creatorId: "evolution-game", creatorName: "Evolution Game", creatorLabel: "BY EVOLUTION GAME · LOCAL SOURCE MIRROR", category: "Arcade" },
  "porki-poke": { creatorId: "porki-poke", creatorName: "Porki Poke", creatorLabel: "BY PORKI POKE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "squid-dash": { creatorId: "squid-dash", creatorName: "Squid Dash", creatorLabel: "BY SQUID DASH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blocky-out": { creatorId: "blocky-out", creatorName: "Blocky Out", creatorLabel: "BY BLOCKY OUT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "rumble-rush": { creatorId: "rumble-rush", creatorName: "Rumble Rush", creatorLabel: "BY RUMBLE RUSH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "beach-boxing-simulator": { creatorId: "beach-boxing-simulator", creatorName: "Beach Boxing Simulator", creatorLabel: "BY BEACH BOXING SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "drills-merge-master": { creatorId: "drills-merge-master", creatorName: "Drills Merge Master", creatorLabel: "BY DRILLS MERGE MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "right-jump": { creatorId: "right-jump", creatorName: "Right Jump", creatorLabel: "BY RIGHT JUMP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "i-am-hall-security": { creatorId: "i-am-hall-security", creatorName: "I Am Hall Security", creatorLabel: "BY I AM HALL SECURITY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "meme-madness": { creatorId: "meme-madness", creatorName: "Meme Madness", creatorLabel: "BY MEME MADNESS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "buck-bounce": { creatorId: "buck-bounce", creatorName: "Buck Bounce", creatorLabel: "BY BUCK BOUNCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kigurumi-dress-up": { creatorId: "kigurumi-dress-up", creatorName: "Kigurumi Dress Up", creatorLabel: "BY KIGURUMI DRESS UP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bee-sort-by-sam": { creatorId: "bee-sort-by-sam", creatorName: "Bee Sort by Sam", creatorLabel: "BY BEE SORT BY SAM · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cafe-bara": { creatorId: "cafe-bara", creatorName: "Cafe Bara", creatorLabel: "BY CAFE BARA · LOCAL SOURCE MIRROR", category: "Arcade" },
  "a-cleaning-story": { creatorId: "a-cleaning-story", creatorName: "A Cleaning Story", creatorLabel: "BY A CLEANING STORY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cube-miner-escape-from-prison": { creatorId: "cube-miner", creatorName: "Cube Miner", creatorLabel: "BY CUBE MINER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "the-superhero-league": { creatorId: "the-superhero-league", creatorName: "The Superhero League", creatorLabel: "BY THE SUPERHERO LEAGUE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snow-plow": { creatorId: "snow-plow", creatorName: "Snow Plow", creatorLabel: "BY SNOW PLOW · LOCAL SOURCE MIRROR", category: "Arcade" },
  "morph-balls": { creatorId: "morph-balls", creatorName: "Morph Balls", creatorLabel: "BY MORPH BALLS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "block-sandbox": { creatorId: "block-sandbox", creatorName: "Block Sandbox", creatorLabel: "BY BLOCK SANDBOX · LOCAL SOURCE MIRROR", category: "Arcade" },
  "diva-hair-salon": { creatorId: "diva-hair-salon", creatorName: "Diva Hair Salon", creatorLabel: "BY DIVA HAIR SALON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "screw-jam-puzzle": { creatorId: "screw-jam-puzzle", creatorName: "Screw Jam Puzzle", creatorLabel: "BY SCREW JAM PUZZLE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "need-for-madness": { creatorId: "need-for-madness", creatorName: "Need for Madness", creatorLabel: "BY NEED FOR MADNESS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pets-park": { creatorId: "pets-park", creatorName: "Pets Park", creatorLabel: "BY PETS PARK · LOCAL SOURCE MIRROR", category: "Arcade" },
  "doodle-race": { creatorId: "doodle-race", creatorName: "Doodle Race", creatorLabel: "BY DOODLE RACE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "heroes-league": { creatorId: "heroes-league", creatorName: "Heroes League", creatorLabel: "BY HEROES LEAGUE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "coin-machine": { creatorId: "coin-machine", creatorName: "Coin Machine", creatorLabel: "BY COIN MACHINE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "flying-wheels-evolution": { creatorId: "flying-wheels-evolution", creatorName: "Flying Wheels Evolution", creatorLabel: "BY FLYING WHEELS EVOLUTION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "crazy-descent": { creatorId: "crazy-descent", creatorName: "Crazy Descent", creatorLabel: "BY CRAZY DESCENT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ant-art-tycoon": { creatorId: "ant-art-tycoon", creatorName: "Ant Art Tycoon", creatorLabel: "BY ANT ART TYCOON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "run-3": { creatorId: "run-3", creatorName: "Run 3", creatorLabel: "BY RUN 3 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blockpost": { creatorId: "blockpost", creatorName: "Blockpost", creatorLabel: "BY BLOCKPOST · LOCAL SOURCE MIRROR", category: "Arcade" },
  "blockpost-legacy": { creatorId: "blockpost-legacy", creatorName: "Blockpost Legacy", creatorLabel: "BY BLOCKPOST LEGACY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "jetpack-fury": { creatorId: "jetpack-fury", creatorName: "Jetpack Fury", creatorLabel: "BY JETPACK FURY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "digger-escape": { creatorId: "digger-escape", creatorName: "Digger Escape", creatorLabel: "BY DIGGER ESCAPE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "auto-ninja": { creatorId: "auto-ninja", creatorName: "Auto Ninja", creatorLabel: "BY AUTO NINJA · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moving-blocks": { creatorId: "moving-blocks", creatorName: "Moving Blocks", creatorLabel: "BY MOVING BLOCKS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cougar-simulator-big-cats": { creatorId: "cougar-simulator-big-cats", creatorName: "Cougar Simulator: Big Cats", creatorLabel: "BY COUGAR SIMULATOR: BIG CATS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "schools-out-the-great-escape": { creatorId: "school-s-out", creatorName: "School's Out", creatorLabel: "BY SCHOOL'S OUT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "basketball-superstars": { creatorId: "basketball-superstars", creatorName: "Basketball Superstars", creatorLabel: "BY BASKETBALL SUPERSTARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "gobattle2": { creatorId: "gobattle-2", creatorName: "GoBattle 2", creatorLabel: "BY GOBATTLE 2 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "samurai-punch": { creatorId: "samurai-punch", creatorName: "Samurai Punch", creatorLabel: "BY SAMURAI PUNCH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brainrot-clicker": { creatorId: "brainrot-clicker", creatorName: "Brainrot Clicker", creatorLabel: "BY BRAINROT CLICKER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "elemental-master": { creatorId: "elemental-master", creatorName: "Elemental Master", creatorLabel: "BY ELEMENTAL MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "merge-zoo": { creatorId: "merge-zoo", creatorName: "Merge Zoo", creatorLabel: "BY MERGE ZOO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dino-miner": { creatorId: "dino-miner", creatorName: "Dino Miner", creatorLabel: "BY DINO MINER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bounce-ball": { creatorId: "bounce-ball", creatorName: "Bounce Ball", creatorLabel: "BY BOUNCE BALL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "circloo-xl": { creatorId: "circloo-xl", creatorName: "circloO XL", creatorLabel: "BY CIRCLOO XL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brainrot-craft": { creatorId: "brainrot-craft", creatorName: "Brainrot Craft", creatorLabel: "BY BRAINROT CRAFT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tower-merge": { creatorId: "tower-merge", creatorName: "Tower Merge", creatorLabel: "BY TOWER MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "plane-wars": { creatorId: "plane-wars", creatorName: "Plane Wars", creatorLabel: "BY PLANE WARS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cozy-garden-design": { creatorId: "cozy-garden-design", creatorName: "Cozy Garden Design", creatorLabel: "BY COZY GARDEN DESIGN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "nekopirate-quest-for-gold": { creatorId: "nekopirate-quest-for-gold", creatorName: "Nekopirate: Quest for Gold!", creatorLabel: "BY NEKOPIRATE: QUEST FOR GOLD! · LOCAL SOURCE MIRROR", category: "Arcade" },
  "flick-goal": { creatorId: "flick-goal", creatorName: "Flick Goal", creatorLabel: "BY FLICK GOAL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "duel-of-chance": { creatorId: "duel-of-chance", creatorName: "Duel of Chance", creatorLabel: "BY DUEL OF CHANCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cow-castle": { creatorId: "cow-castle", creatorName: "Cow Castle", creatorLabel: "BY COW CASTLE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "perfect-landing-plane-pilot": { creatorId: "perfect-landing-plane-pilot", creatorName: "Perfect Landing, Plane Pilot", creatorLabel: "BY PERFECT LANDING, PLANE PILOT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "my-cozy-home": { creatorId: "my-cozy-home", creatorName: "My Cozy Home", creatorLabel: "BY MY COZY HOME · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ranch-ufo": { creatorId: "ranch-ufo", creatorName: "Ranch UFO", creatorLabel: "BY RANCH UFO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "hot-air": { creatorId: "hot-air", creatorName: "Hot Air", creatorLabel: "BY HOT AIR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "master-assassin": { creatorId: "master-assassin", creatorName: "Master Assassin", creatorLabel: "BY MASTER ASSASSIN · LOCAL SOURCE MIRROR", category: "Arcade" },
  "drift-boss": {
    creatorId: "poki-mirror",
    creatorName: "Drift Boss",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Runner",
  },
  "penalty-shooters-2": {
    creatorId: "nuspeko",
    creatorName: "NUSPEKO",
    creatorLabel: "BY NUSPEKO · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "soccer-real": {
    creatorId: "y8",
    creatorName: "Y8",
    creatorLabel: "BY Y8 · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "master-chess": {
    creatorId: "codethislab",
    creatorName: "Codethislab",
    creatorLabel: "BY CODETHISLAB · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "basketball-stars": {
    creatorId: "madbox",
    creatorName: "Madbox",
    creatorLabel: "BY MADBOX · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "stickman-hook": {
    creatorId: "madbox",
    creatorName: "Madbox",
    creatorLabel: "BY MADBOX · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "happy-glass": {
    creatorId: "lion-studios",
    creatorName: "Lion Studios",
    creatorLabel: "BY LION STUDIOS · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "drive-mad": {
    creatorId: "fancade",
    creatorName: "Fancade",
    creatorLabel: "BY FANCADE · LOCAL SOURCE MIRROR",
    category: "Arcade",
  },
  "slice-master": {
    creatorId: "kwalee",
    creatorName: "Kwalee",
    creatorLabel: "BY KWALEE · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "level-devil": {
    creatorId: "unept",
    creatorName: "Unept",
    creatorLabel: "BY UNEPT · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "game-2048": {
    creatorId: "gabrielecirulli",
    creatorName: "Gabriele Cirulli",
    creatorLabel: "BY GABRIELE CIRULLI · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "ping-pong-bugs": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER · TIP TAP INTEGRATION",
    category: "Sports",
  },
};

const FALLBACK_METADATA: GameCatalogMetadata = {
  creatorId: "tiptap",
  creatorName: "Tip Tap",
  creatorLabel: "@tiptap",
  category: "Arcade",
};

export function getGameCatalogMetadata(slug: string): GameCatalogMetadata {
  return GAME_CATALOG_METADATA[slug] ?? FALLBACK_METADATA;
}

export const CREATOR_IDS = new Set(
  Object.values(GAME_CATALOG_METADATA).map((game) => game.creatorId),
);
