export type GameCategory = "Action" | "Arcade" | "Puzzle" | "Runner" | "Sports";

export interface GameCatalogMetadata {
  creatorId: string;
  creatorName: string;
  creatorLabel: string;
  category: GameCategory;
}

export const GAME_CATALOG_METADATA: Record<string, GameCatalogMetadata> = {
  "pulse-lock": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "color-clash": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Puzzle",
  },
  "stack-shift": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "memory-grid": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Puzzle",
  },
  "meteor-dodge": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Originals",
    creatorLabel: "@tiptap · ORIGINAL",
    category: "Arcade",
  },
  "subway-surfers": {
    creatorId: "sybo",
    creatorName: "SYBO",
    creatorLabel: "BY SYBO · TIP TAP INTEGRATION",
    category: "Runner",
  },
  "dino-runner": {
    creatorId: "chrome-ux",
    creatorName: "Chrome UX",
    creatorLabel: "BY CHROME UX · TIP TAP INTEGRATION",
    category: "Runner",
  },
  arithmetica: {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Puzzle",
  },
  "67-game": {
    creatorId: "stupidella",
    creatorName: "Stupidella",
    creatorLabel: "BY STUPIDELLA · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "archery-king": {
    creatorId: "code-this-lab",
    creatorName: "Code This Lab",
    creatorLabel: "BY CODE THIS LAB · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "smash-room": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER LTD · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "temple-run-2-frozen-shadows": {
    creatorId: "imangi",
    creatorName: "Imangi Studios",
    creatorLabel: "BY IMANGI STUDIOS · LOCAL SOURCE MIRROR",
    category: "Runner",
  },
  "stickman-fury": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER LTD · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  plonky: {
    creatorId: "gametornado",
    creatorName: "GameTornado",
    creatorLabel: "BY GAMETORNADO · LOCAL SOURCE MIRROR",
    category: "Arcade",
  },
  "fruit-ninja": {
    creatorId: "storms",
    creatorName: "Storms",
    creatorLabel: "BY STORMS · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "count-control-legends": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Runner",
  },
  "johnny-trigger-sniper": {
    creatorId: "saygames",
    creatorName: "SayGames",
    creatorLabel: "BY SAYGAMES · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "rocket-soccer-derby": {
    creatorId: "destruction-crew",
    creatorName: "Destruction Crew",
    creatorLabel: "BY DESTRUCTION CREW · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "dig-out-of-prison": {
    creatorId: "incredi-games",
    creatorName: "Incredi.Games",
    creatorLabel: "BY INCREDI.GAMES · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "kitty-loves-birds-2": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Runner",
  },
  "theft-city": {
    creatorId: "tiptap",
    creatorName: "Tip Tap Integrations",
    creatorLabel: "@tiptap · INTEGRATION",
    category: "Action",
  },
  "city-cab-rush": {
    creatorId: "storerider",
    creatorName: "StoreRider",
    creatorLabel: "BY STORERIDER · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "supercar-legends": {
    creatorId: "jungle-tavern",
    creatorName: "Jungle Tavern",
    creatorLabel: "BY JUNGLE TAVERN · TIP TAP INTEGRATION",
    category: "Runner",
  },
  "ping-pong-go": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER · TIP TAP INTEGRATION",
    category: "Sports",
  },
  "tic-tac-toe": {
    creatorId: "cocos-dev",
    creatorName: "Cocos Creator",
    creatorLabel: "BY COCOS CREATOR · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "go-battle-2": {
    creatorId: "poki-mirror",
    creatorName: "Go Battle 2",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "stickman-battle": {
    creatorId: "poki-mirror",
    creatorName: "Stickman Battle",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "retro-bowl": {
    creatorId: "poki-mirror",
    creatorName: "Retro Bowl",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "domino": { creatorId: "domino", creatorName: "Domino", creatorLabel: "BY DOMINO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "foosball": { creatorId: "foosball", creatorName: "Foosball", creatorLabel: "BY FOOSBALL · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ludo-hero": { creatorId: "ludo-hero", creatorName: "Ludo Hero", creatorLabel: "BY LUDO HERO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moto-x3m": { creatorId: "moto-x3m", creatorName: "Moto X3M", creatorLabel: "BY MOTO X3M · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubble-storm": { creatorId: "bubble-storm", creatorName: "Bubble Storm", creatorLabel: "BY BUBBLE STORM · LOCAL SOURCE MIRROR", category: "Arcade" },
  "spider-solitaire": { creatorId: "chrome-and-opera", creatorName: "Chrome and Opera", creatorLabel: "BY CHROME AND OPERA · LOCAL SOURCE MIRROR", category: "Arcade" },
  "master-checkers": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "four-in-a-row": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "monkey-mart": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "eggy-car": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiny-fishing": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "beauty-salon": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fashion-fix-studio": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "phone-case-diy": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "clean-house": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "stunt-bike-extreme": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "idle-lumber-inc": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "my-perfect-hotel": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snapstyle-dress-up": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "brain-test-tricky-puzzles": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "little-farm-world": { creatorId: "little-farm-world", creatorName: "Little Farm World", creatorLabel: "BY LITTLE FARM WORLD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moms-diary-cooking-games": { creatorId: "mom-s-diary-cooking-games", creatorName: "Mom's Diary Cooking Games", creatorLabel: "BY MOM'S DIARY COOKING GAMES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "scary-teacher-hide-seek-games": { creatorId: "scary-teacher-hide-seek-games", creatorName: "Scary Teacher Hide & Seek Games", creatorLabel: "BY SCARY TEACHER HIDE & SEEK GAMES · LOCAL SOURCE MIRROR", category: "Arcade" },
  "demolition-simulator": { creatorId: "demolition-simulator", creatorName: "Demolition Simulator", creatorLabel: "BY DEMOLITION SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "family-sort": { creatorId: "family-sort", creatorName: "Family Sort", creatorLabel: "BY FAMILY SORT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "kick-the-buddy": { creatorId: "kick-the-buddy", creatorName: "Kick The Buddy", creatorLabel: "BY KICK THE BUDDY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "slime-keyboard-escape": { creatorId: "slime-keyboard-escape", creatorName: "Slime Keyboard Escape", creatorLabel: "BY SLIME KEYBOARD ESCAPE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dragon-the-dragon": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "pet-mahjong-3d": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "petnest-io": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "travel-merge": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "build-your-island": { creatorId: "build-your-island", creatorName: "Build Your Island", creatorLabel: "BY BUILD YOUR ISLAND · LOCAL SOURCE MIRROR", category: "Arcade" },
  "sandbox-of-elements": { creatorId: "sandbox-of-elements", creatorName: "Sandbox of Elements", creatorLabel: "BY SANDBOX OF ELEMENTS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "crowd-rush": { creatorId: "crowd-rush", creatorName: "Crowd Rush", creatorLabel: "BY CROWD RUSH · LOCAL SOURCE MIRROR", category: "Arcade" },
  "harvest-loop": { creatorId: "harvest-loop", creatorName: "Harvest Loop", creatorLabel: "BY HARVEST LOOP · LOCAL SOURCE MIRROR", category: "Arcade" },
  "tiny-game-shop-tycoon": { creatorId: "tiny-game-shop-tycoon", creatorName: "Tiny Game Shop Tycoon", creatorLabel: "BY TINY GAME SHOP TYCOON · LOCAL SOURCE MIRROR", category: "Arcade" },
  "undead-slayer": { creatorId: "undead-slayer", creatorName: "Undead Slayer", creatorLabel: "BY UNDEAD SLAYER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "knife-merge": { creatorId: "knife-merge", creatorName: "Knife Merge", creatorLabel: "BY KNIFE MERGE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "family-life-simulator": { creatorId: "family-life-simulator", creatorName: "Family Life Simulator", creatorLabel: "BY FAMILY LIFE SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dummies-fight": { creatorId: "dummies-fight", creatorName: "Dummies Fight", creatorLabel: "BY DUMMIES FIGHT · LOCAL SOURCE MIRROR", category: "Arcade" },
  "perfect-shape": { creatorId: "perfect-shape", creatorName: "Perfect Shape", creatorLabel: "BY PERFECT SHAPE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "flip-pounce": { creatorId: "flip-pounce", creatorName: "Flip Pounce", creatorLabel: "BY FLIP POUNCE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "goalheads-io": { creatorId: "goalheads-io", creatorName: "GoalHeads.io", creatorLabel: "BY GOALHEADS.IO · LOCAL SOURCE MIRROR", category: "Arcade" },
  "goods-master": { creatorId: "goods-master", creatorName: "Goods Master", creatorLabel: "BY GOODS MASTER · LOCAL SOURCE MIRROR", category: "Arcade" },
  "20f8": { creatorId: "20f8", creatorName: "20f8", creatorLabel: "BY 20F8 · LOCAL SOURCE MIRROR", category: "Arcade" },
  "fashion-dress-up-star": { creatorId: "fashion-dress-up-star", creatorName: "Fashion Dress Up Star", creatorLabel: "BY FASHION DRESS UP STAR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dino-simulator": { creatorId: "dino-simulator", creatorName: "Dino Simulator", creatorLabel: "BY DINO SIMULATOR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "bubbleshooter-x-basketball-3d": { creatorId: "bubbleshooter-x-basketball-3d", creatorName: "Bubbleshooter x Basketball 3D", creatorLabel: "BY BUBBLESHOOTER X BASKETBALL 3D · LOCAL SOURCE MIRROR", category: "Arcade" },
  "boomy-world": { creatorId: "boomy-world", creatorName: "Boomy World", creatorLabel: "BY BOOMY WORLD · LOCAL SOURCE MIRROR", category: "Arcade" },
  "chick-flix": { creatorId: "chick-flix", creatorName: "Chick Flix", creatorLabel: "BY CHICK FLIX · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ball-guys": { creatorId: "ball-guys", creatorName: "Ball Guys", creatorLabel: "BY BALL GUYS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "color-shapes": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "paperio-2": { creatorId: "merci-michel-preproduction", creatorName: "Merci-Michel Preproduction", creatorLabel: "BY MERCI-MICHEL PREPRODUCTION · LOCAL SOURCE MIRROR", category: "Arcade" },
  "snow-yeet": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "robo-cleaner-simulator": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "noob-archer-2": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "carnado-boat-racing": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "super-dress": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "block-for-blood": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "dress-up-party": { creatorId: "dress-up-party", creatorName: "Dress Up Party", creatorLabel: "BY DRESS UP PARTY · LOCAL SOURCE MIRROR", category: "Arcade" },
  "cuboy-adventure": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "ragdoll-chaos": { creatorId: "ragdoll-chaos", creatorName: "Ragdoll Chaos", creatorLabel: "BY RAGDOLL CHAOS · LOCAL SOURCE MIRROR", category: "Arcade" },
  "critter-chaos": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "happy-tidy-time": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "soccer-league": { creatorId: "soccer-league", creatorName: "Soccer League", creatorLabel: "BY SOCCER LEAGUE · LOCAL SOURCE MIRROR", category: "Arcade" },
  "moto-trap": { creatorId: "poki-mirror", creatorName: "Poki Mirror", creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR", category: "Arcade" },
  "drift-boss": {
    creatorId: "poki-mirror",
    creatorName: "Drift Boss",
    creatorLabel: "BY POKI MIRROR · LOCAL SOURCE MIRROR",
    category: "Runner",
  },
  "penalty-shooters-2": {
    creatorId: "nuspeko",
    creatorName: "NUSPEKO",
    creatorLabel: "BY NUSPEKO · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "soccer-real": {
    creatorId: "y8",
    creatorName: "Y8",
    creatorLabel: "BY Y8 · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "master-chess": {
    creatorId: "codethislab",
    creatorName: "Codethislab",
    creatorLabel: "BY CODETHISLAB · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "basketball-stars": {
    creatorId: "madbox",
    creatorName: "Madbox",
    creatorLabel: "BY MADBOX · LOCAL SOURCE MIRROR",
    category: "Sports",
  },
  "stickman-hook": {
    creatorId: "madbox",
    creatorName: "Madbox",
    creatorLabel: "BY MADBOX · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "happy-glass": {
    creatorId: "lion-studios",
    creatorName: "Lion Studios",
    creatorLabel: "BY LION STUDIOS · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "drive-mad": {
    creatorId: "fancade",
    creatorName: "Fancade",
    creatorLabel: "BY FANCADE · LOCAL SOURCE MIRROR",
    category: "Arcade",
  },
  "slice-master": {
    creatorId: "kwalee",
    creatorName: "Kwalee",
    creatorLabel: "BY KWALEE · LOCAL SOURCE MIRROR",
    category: "Action",
  },
  "level-devil": {
    creatorId: "unept",
    creatorName: "Unept",
    creatorLabel: "BY UNEPT · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "game-2048": {
    creatorId: "gabrielecirulli",
    creatorName: "Gabriele Cirulli",
    creatorLabel: "BY GABRIELE CIRULLI · LOCAL SOURCE MIRROR",
    category: "Puzzle",
  },
  "ping-pong-bugs": {
    creatorId: "happylander",
    creatorName: "Happylander",
    creatorLabel: "BY HAPPYLANDER · TIP TAP INTEGRATION",
    category: "Sports",
  },
};

const FALLBACK_METADATA: GameCatalogMetadata = {
  creatorId: "tiptap",
  creatorName: "Tip Tap",
  creatorLabel: "@tiptap",
  category: "Arcade",
};

export function getGameCatalogMetadata(slug: string): GameCatalogMetadata {
  return GAME_CATALOG_METADATA[slug] ?? FALLBACK_METADATA;
}

export const CREATOR_IDS = new Set(
  Object.values(GAME_CATALOG_METADATA).map((game) => game.creatorId),
);
