import type { BootstrapData } from "./types";

export const OFFLINE_BOOTSTRAP: BootstrapData = {
  player: {
    id: "offline-practice",
    handle: "OFFLINE",
    avatarUrl: null,
    provider: "guest",
    isGuest: true,
  },
  games: [
    {
      slug: "pulse-lock",
      title: "Pulse Lock",
      rule_text: "Tap when the pulse hits the live zone.",
      accent: "#38b6ff",
    },
    {
      slug: "color-clash",
      title: "Color Clash",
      rule_text: "Tap the color named, not the color shown.",
      accent: "#b06cff",
    },
    {
      slug: "stack-shift",
      title: "Stack Shift",
      rule_text: "Tap to lock each moving block in place.",
      accent: "#21d4fd",
    },
    {
      slug: "memory-grid",
      title: "Memory Grid",
      rule_text: "Watch the signal. Repeat the growing pattern.",
      accent: "#ff4fd8",
    },
    {
      slug: "meteor-dodge",
      title: "Meteor Dodge",
      rule_text: "Drag sideways. Stay clear of every meteor.",
      accent: "#ff9f1c",
    },
    {
      slug: "subway-surfers",
      title: "Subway Surfers",
      rule_text: "Swipe to dodge trains, jump barriers, and chase the highest score.",
      accent: "#ffd32a",
    },
    {
      slug: "dino-runner",
      title: "Dino Runner",
      rule_text: "Tap to jump. Survive the endless desert.",
      accent: "#4ade80",
    },
    {
      slug: "arithmetica",
      title: "ArithmeticA",
      rule_text: "Solve the math. Beat the clock.",
      accent: "#f59e0b",
    },
    {
      slug: "67-game",
      title: "67 Game",
      rule_text: "Solve rapid-fire puzzle levels before the clock runs out.",
      accent: "#fe930e",
    },
    {
      slug: "archery-king",
      title: "Archery King",
      rule_text: "Draw, aim with the wind, and hit the target in 24 solo levels.",
      accent: "#ef4444",
    },
    {
      slug: "smash-room",
      title: "Smash Room",
      rule_text: "Choose a tool and smash every voxel object in sight.",
      accent: "#fb923c",
    },
    {
      slug: "temple-run-2-frozen-shadows",
      title: "Temple Run 2: Frozen Shadows",
      rule_text: "Run the frozen path. Swipe to turn, jump, and slide past every trap.",
      accent: "#b7e6ff",
    },
    {
      slug: "stickman-fury",
      title: "Stickman Fury",
      rule_text: "Move, jump, fight, and survive every physics-driven arena.",
      accent: "#ef4444",
      ranked: false,
    },
    {
      slug: "plonky",
      title: "Plonky",
      rule_text: "Run, jump, and outsmart the traps.",
      accent: "#1dd7d7",
    },
    {
      slug: "fruit-ninja",
      title: "Fruit Ninja",
      rule_text: "Swipe to slice fruit for points. Avoid the bombs.",
      accent: "#84cc16",
    },
    {
      slug: "count-control-legends",
      title: "Count Control Legends",
      rule_text: "Move left and right, grow your crew through the best number gates, and conquer the course.",
      accent: "#38bdf8",
    },
    {
      slug: "johnny-trigger-sniper",
      title: "Johnny Trigger - Sniper Game",
      rule_text: "Aim carefully, eliminate the targets, and protect civilians.",
      accent: "#00c565",
      ranked: false,
    },
    {
      slug: "rocket-soccer-derby",
      title: "Rocket Soccer Derby",
      rule_text: "Drive, boost, hit the ball, and score more goals than your opponent.",
      accent: "#ff7a47",
      ranked: false,
    },
    {
      slug: "dig-out-of-prison",
      title: "Dig out of Prison",
      rule_text: "Dig, gather resources, and escape the prison compound.",
      accent: "#7bcf63",
      ranked: false,
    },
    {
      slug: "theft-city",
      title: "Theft City",
      rule_text: "Explore the city, collect loot, escape danger, and build your criminal empire.",
      accent: "#facc15",
    },
    {
      slug: "city-cab-rush",
      title: "City Cab Rush",
      rule_text: "Drive through traffic, pick up fares, and race to the destination.",
      accent: "#fbbf24",
    },
    {
      slug: "supercar-legends",
      title: "Supercar Legends",
      rule_text: "Swipe left/right through math gates. Grow your run.",
      accent: "#ff3b6b",
    },
    {
      slug: "ping-pong-go",
      title: "Ping Pong Go",
      rule_text: "Swipe to serve and rally. Win every point against the CPU.",
      accent: "#06b6d4",
    },
    {
      slug: "soccer-real",
      title: "Soccer REAL",
      rule_text: "Score more than the keeper can save.",
      accent: "#4ade80",
    },
    {
      slug: "master-chess",
      title: "Master Chess",
      rule_text: "Checkmate the master. Every move counts.",
      accent: "#a78bfa",
    },
    {
      slug: "basketball-stars",
      title: "Basketball Stars",
      rule_text: "Outscore the rival. Sink the buzzer-beater.",
      accent: "#fb923c",
    },
    {
      slug: "stickman-hook",
      title: "Stickman Hook",
      rule_text: "Swing through the course. Don't let go.",
      accent: "#f472b6",
    },
    {
      slug: "happy-glass",
      title: "Happy Glass",
      rule_text: "Draw the line. Fill the glass.",
      accent: "#38bdf8",
    },
    {
      slug: "drive-mad",
      title: "Drive Mad",
      rule_text: "Race the road. Flip the finish.",
      accent: "#22c55e",
    },
    {
      slug: "slice-master",
      title: "Slice Master",
      rule_text: "Slice every object. Miss nothing.",
      accent: "#ff8a00",
    },
    {
      slug: "level-devil",
      title: "Level Devil",
      rule_text: "Climb the tower. Every floor is out to get you.",
      accent: "#ef4444",
    },
    {
      slug: "game-2048",
      title: "2048",
      rule_text: "Swipe to merge tiles and reach 2048.",
      accent: "#edc22e",
    },
    {
      slug: "ping-pong-bugs",
      title: "Ping Pong Bugs",
      rule_text: "Smash every wave of bugs off the table before they land.",
      accent: "#d946ef",
    },
  ],
  likes: {},
  engagement: {},
  followedCreatorIds: [],
  stats: {
    rankedRuns: 0,
    rankedGames: 0,
    savedGames: 0,
    followingCreators: 0,
  },
  auth: { google: false, discord: false },
};
