import type { BootstrapData } from "./types";

export const OFFLINE_BOOTSTRAP: BootstrapData = {
  player: {
    id: "offline-practice",
    handle: "OFFLINE",
    avatarUrl: null,
    provider: "guest",
    isGuest: true,
  },
  games: [
    {
      slug: "pulse-lock",
      title: "Pulse Lock",
      rule_text: "Tap when the pulse hits the live zone.",
      accent: "#38b6ff",
    },
    {
      slug: "color-clash",
      title: "Color Clash",
      rule_text: "Tap the color named, not the color shown.",
      accent: "#b06cff",
    },
    {
      slug: "stack-shift",
      title: "Stack Shift",
      rule_text: "Tap to lock each moving block in place.",
      accent: "#21d4fd",
    },
    {
      slug: "memory-grid",
      title: "Memory Grid",
      rule_text: "Watch the signal. Repeat the growing pattern.",
      accent: "#ff4fd8",
    },
    {
      slug: "meteor-dodge",
      title: "Meteor Dodge",
      rule_text: "Drag sideways. Stay clear of every meteor.",
      accent: "#ff9f1c",
    },
    {
      slug: "subway-surfers",
      title: "Subway Surfers",
      rule_text: "Swipe to dodge trains, jump barriers, and chase the highest score.",
      accent: "#ffd32a",
    },
    {
      slug: "dino-runner",
      title: "Dino Runner",
      rule_text: "Tap to jump. Survive the endless desert.",
      accent: "#4ade80",
    },
    {
      slug: "arithmetica",
      title: "ArithmeticA",
      rule_text: "Solve the math. Beat the clock.",
      accent: "#f59e0b",
    },
    {
      slug: "67-game",
      title: "67 Game",
      rule_text: "Solve rapid-fire puzzle levels before the clock runs out.",
      accent: "#fe930e",
    },
    {
      slug: "archery-king",
      title: "Archery King",
      rule_text: "Draw, aim with the wind, and hit the target in 24 solo levels.",
      accent: "#ef4444",
    },
    {
      slug: "smash-room",
      title: "Smash Room",
      rule_text: "Choose a tool and smash every voxel object in sight.",
      accent: "#fb923c",
    },
    {
      slug: "temple-run-2-frozen-shadows",
      title: "Temple Run 2: Frozen Shadows",
      rule_text: "Run the frozen path. Swipe to turn, jump, and slide past every trap.",
      accent: "#b7e6ff",
    },
    {
      slug: "stickman-fury",
      title: "Stickman Fury",
      rule_text: "Move, jump, fight, and survive every physics-driven arena.",
      accent: "#ef4444",
      ranked: false,
    },
    {
      slug: "plonky",
      title: "Plonky",
      rule_text: "Run, jump, and outsmart the traps.",
      accent: "#1dd7d7",
    },
    {
      slug: "fruit-ninja",
      title: "Fruit Ninja",
      rule_text: "Swipe to slice fruit for points. Avoid the bombs.",
      accent: "#84cc16",
    },
    {
      slug: "count-control-legends",
      title: "Count Control Legends",
      rule_text: "Move left and right, grow your crew through the best number gates, and conquer the course.",
      accent: "#38bdf8",
    },
    {
      slug: "johnny-trigger-sniper",
      title: "Johnny Trigger - Sniper Game",
      rule_text: "Aim carefully, eliminate the targets, and protect civilians.",
      accent: "#00c565",
      ranked: false,
    },
    {
      slug: "rocket-soccer-derby",
      title: "Rocket Soccer Derby",
      rule_text: "Drive, boost, hit the ball, and score more goals than your opponent.",
      accent: "#ff7a47",
      ranked: false,
    },
    {
      slug: "dig-out-of-prison",
      title: "Dig out of Prison",
      rule_text: "Dig, gather resources, and escape the prison compound.",
      accent: "#7bcf63",
      ranked: false,
    },
    {
      slug: "theft-city",
      title: "Theft City",
      rule_text: "Explore the city, collect loot, escape danger, and build your criminal empire.",
      accent: "#facc15",
    },
    {
      slug: "city-cab-rush",
      title: "City Cab Rush",
      rule_text: "Drive through traffic, pick up fares, and race to the destination.",
      accent: "#fbbf24",
    },
    {
      slug: "supercar-legends",
      title: "Supercar Legends",
      rule_text: "Swipe left/right through math gates. Grow your run.",
      accent: "#ff3b6b",
    },
    {
      slug: "ping-pong-go",
      title: "Ping Pong Go",
      rule_text: "Swipe to serve and rally. Win every point against the CPU.",
      accent: "#06b6d4",
    },
    {
      slug: "tic-tac-toe",
      title: "Tic Tac Toe",
      rule_text: "Three in a row. Every game, every time.",
      accent: "#38bdf8",
    },
    {
      slug: "go-battle-2",
      title: "Go Battle 2",
      rule_text: "Win the arena. Battle for the top.",
      accent: "#f97316",
    },
    {
      slug: "stickman-battle",
      title: "Stickman Battle",
      rule_text: "Fight through the arena. Last one standing wins.",
      accent: "#ef4444",
    },
    {
      slug: "retro-bowl",
      title: "Retro Bowl",
      rule_text: "Lead your team to the championship.",
      accent: "#22c55e",
    },
    { slug: "domino", title: "domino", rule_text: "Play domino.", accent: "#8b5cf6" },
    { slug: "foosball", title: "foosball", rule_text: "Play foosball.", accent: "#8b5cf6" },
    { slug: "ludo-hero", title: "ludo-hero", rule_text: "Play ludo-hero.", accent: "#8b5cf6" },
    { slug: "moto-x3m", title: "moto-x3m", rule_text: "Play moto-x3m.", accent: "#8b5cf6" },
    { slug: "bubble-storm", title: "bubble-storm", rule_text: "Play bubble-storm.", accent: "#8b5cf6" },
    { slug: "spider-solitaire", title: "Spider Solitaire Plus", rule_text: "Play Spider Solitaire Plus.", accent: "#8b5cf6" },
    { slug: "master-checkers", title: "master-checkers", rule_text: "Play master-checkers.", accent: "#8b5cf6" },
    { slug: "four-in-a-row", title: "four-in-a-row", rule_text: "Play four-in-a-row.", accent: "#8b5cf6" },
    { slug: "monkey-mart", title: "MonkeyMart", rule_text: "Play MonkeyMart.", accent: "#8b5cf6" },
    { slug: "eggy-car", title: "Eggy Car", rule_text: "Play Eggy Car.", accent: "#8b5cf6" },
    { slug: "tiny-fishing", title: "Tiny Fishing by buyhtml5.com", rule_text: "Play Tiny Fishing by buyhtml5.com.", accent: "#8b5cf6" },
    { slug: "beauty-salon", title: "BeautySalon", rule_text: "Play BeautySalon.", accent: "#8b5cf6" },
    { slug: "fashion-fix-studio", title: "Fashion Fix Studio", rule_text: "Play Fashion Fix Studio.", accent: "#8b5cf6" },
    { slug: "phone-case-diy", title: "Case Coloring", rule_text: "Play Case Coloring.", accent: "#8b5cf6" },
    { slug: "clean-house", title: "Clean House - Poki", rule_text: "Play Clean House - Poki.", accent: "#8b5cf6" },
    { slug: "stunt-bike-extreme", title: "Stunt Bike Extreme - Poki", rule_text: "Play Stunt Bike Extreme - Poki.", accent: "#8b5cf6" },
    { slug: "idle-lumber-inc", title: "Idle Lumber Inc - Poki", rule_text: "Play Idle Lumber Inc - Poki.", accent: "#8b5cf6" },
    { slug: "my-perfect-hotel", title: "My Perfect Hotel - Poki", rule_text: "Play My Perfect Hotel - Poki.", accent: "#8b5cf6" },
    { slug: "snapstyle-dress-up", title: "SnapStyle Dress-up", rule_text: "Play SnapStyle Dress-up.", accent: "#8b5cf6" },
    { slug: "brain-test-tricky-puzzles", title: "Brain Test", rule_text: "Play Brain Test.", accent: "#8b5cf6" },
    { slug: "dragon-the-dragon", title: "Dragon the Dragon", rule_text: "Play Dragon the Dragon.", accent: "#8b5cf6" },
    { slug: "pet-mahjong-3d", title: "3D Mahjong", rule_text: "Play 3D Mahjong.", accent: "#8b5cf6" },
    { slug: "petnest-io", title: "Petnest.io", rule_text: "Play Petnest.io.", accent: "#8b5cf6" },
    { slug: "travel-merge", title: "Travel Merge 1.11.00", rule_text: "Play Travel Merge 1.11.00.", accent: "#8b5cf6" },
    { slug: "travel-merge", title: "travel-merge", rule_text: "Play travel-merge.", accent: "#8b5cf6" },
    { slug: "dragon-the-dragon", title: "dragon-the-dragon", rule_text: "Play dragon-the-dragon.", accent: "#8b5cf6" },
    { slug: "build-your-island", title: "build-your-island", rule_text: "Play build-your-island.", accent: "#8b5cf6" },
    { slug: "sandbox-of-elements", title: "sandbox-of-elements", rule_text: "Play sandbox-of-elements.", accent: "#8b5cf6" },
    { slug: "crowd-rush", title: "crowd-rush", rule_text: "Play crowd-rush.", accent: "#8b5cf6" },
    { slug: "harvest-loop", title: "harvest-loop", rule_text: "Play harvest-loop.", accent: "#8b5cf6" },
    { slug: "tiny-game-shop-tycoon", title: "tiny-game-shop-tycoon", rule_text: "Play tiny-game-shop-tycoon.", accent: "#8b5cf6" },
    { slug: "undead-slayer", title: "undead-slayer", rule_text: "Play undead-slayer.", accent: "#8b5cf6" },
    { slug: "knife-merge", title: "knife-merge", rule_text: "Play knife-merge.", accent: "#8b5cf6" },
    { slug: "family-life-simulator", title: "family-life-simulator", rule_text: "Play family-life-simulator.", accent: "#8b5cf6" },
    { slug: "dummies-fight", title: "dummies-fight", rule_text: "Play dummies-fight.", accent: "#8b5cf6" },
    { slug: "perfect-shape", title: "perfect-shape", rule_text: "Play perfect-shape.", accent: "#8b5cf6" },
    { slug: "flip-pounce", title: "flip-pounce", rule_text: "Play flip-pounce.", accent: "#8b5cf6" },
    { slug: "goalheads-io", title: "goalheads-io", rule_text: "Play goalheads-io.", accent: "#8b5cf6" },
    { slug: "goods-master", title: "goods-master", rule_text: "Play goods-master.", accent: "#8b5cf6" },
    { slug: "20f8", title: "20f8", rule_text: "Play 20f8.", accent: "#8b5cf6" },
    { slug: "fashion-dress-up-star", title: "fashion-dress-up-star", rule_text: "Play fashion-dress-up-star.", accent: "#8b5cf6" },
    { slug: "dino-simulator", title: "dino-simulator", rule_text: "Play dino-simulator.", accent: "#8b5cf6" },
    { slug: "bubbleshooter-x-basketball-3d", title: "bubbleshooter-x-basketball-3d", rule_text: "Play bubbleshooter-x-basketball-3d.", accent: "#8b5cf6" },
    { slug: "boomy-world", title: "boomy-world", rule_text: "Play boomy-world.", accent: "#8b5cf6" },
    { slug: "chick-flix", title: "chick-flix", rule_text: "Play chick-flix.", accent: "#8b5cf6" },
    { slug: "ball-guys", title: "ball-guys", rule_text: "Play ball-guys.", accent: "#8b5cf6" },
    { slug: "color-shapes", title: "Color Shapes", rule_text: "Play Color Shapes.", accent: "#8b5cf6" },
    { slug: "paperio-2", title: "Paper.io 2", rule_text: "Play Paper.io 2.", accent: "#8b5cf6" },
    { slug: "snow-yeet", title: "Snow Yeet", rule_text: "Play Snow Yeet.", accent: "#8b5cf6" },
    { slug: "robo-cleaner-simulator", title: "robo cleaner", rule_text: "Play robo cleaner.", accent: "#8b5cf6" },
    { slug: "noob-archer-2", title: "Noob Archer 2", rule_text: "Play Noob Archer 2.", accent: "#8b5cf6" },
    { slug: "carnado-boat-racing", title: "Carnado Boat Racing", rule_text: "Play Carnado Boat Racing.", accent: "#8b5cf6" },
    { slug: "super-dress", title: "SuperDress", rule_text: "Play SuperDress.", accent: "#8b5cf6" },
    { slug: "block-for-blood", title: "Block for Blood", rule_text: "Play Block for Blood.", accent: "#8b5cf6" },
    { slug: "dress-up-party", title: "dress-up-party", rule_text: "Play dress-up-party.", accent: "#8b5cf6" },
    { slug: "cuboy-adventure", title: "Cuboy", rule_text: "Play Cuboy.", accent: "#8b5cf6" },
    { slug: "cuboy-adventure", title: "cuboy-adventure", rule_text: "Play cuboy-adventure.", accent: "#8b5cf6" },
    { slug: "ragdoll-chaos", title: "ragdoll-chaos", rule_text: "Play ragdoll-chaos.", accent: "#8b5cf6" },
    { slug: "critter-chaos", title: "Squad CTF Prototype", rule_text: "Play Squad CTF Prototype.", accent: "#8b5cf6" },
    { slug: "happy-tidy-time", title: "Happy Tidy Time", rule_text: "Play Happy Tidy Time.", accent: "#8b5cf6" },
    { slug: "soccer-league", title: "soccer-league", rule_text: "Play soccer-league.", accent: "#8b5cf6" },
    { slug: "moto-trap", title: "biker", rule_text: "Play biker.", accent: "#8b5cf6" },
    { slug: "tiny-baker-ocean-jelly-cake", title: "Tiny Baker Ocean Jelly Cake", rule_text: "Play Tiny Baker Ocean Jelly Cake.", accent: "#8b5cf6" },
    { slug: "robo-cleaner-simulator", title: "robo-cleaner-simulator", rule_text: "Play robo-cleaner-simulator.", accent: "#8b5cf6" },
    { slug: "escape-from-scary-teacher", title: "escape-from-scary-teacher", rule_text: "Play escape-from-scary-teacher.", accent: "#8b5cf6" },
    { slug: "noob-archer-2", title: "noob-archer-2", rule_text: "Play noob-archer-2.", accent: "#8b5cf6" },
    { slug: "dogs-life", title: "dogs-life", rule_text: "Play dogs-life.", accent: "#8b5cf6" },
    { slug: "planet-merge", title: "planet-merge", rule_text: "Play planet-merge.", accent: "#8b5cf6" },
    { slug: "stickman-merge", title: "stickman-merge", rule_text: "Play stickman-merge.", accent: "#8b5cf6" },
    { slug: "jelly-well", title: "jelly-well", rule_text: "Play jelly-well.", accent: "#8b5cf6" },
    { slug: "backrooms-recovery", title: "backrooms-recovery", rule_text: "Play backrooms-recovery.", accent: "#8b5cf6" },
    { slug: "upgrade-the-cars", title: "upgrade-the-cars", rule_text: "Play upgrade-the-cars.", accent: "#8b5cf6" },
    { slug: "mad-skills-rallycross", title: "mad-skills-rallycross", rule_text: "Play mad-skills-rallycross.", accent: "#8b5cf6" },
    { slug: "pull-a-sword", title: "pull-a-sword", rule_text: "Play pull-a-sword.", accent: "#8b5cf6" },
    { slug: "trapped-in-the-dollhouse", title: "trapped-in-the-dollhouse", rule_text: "Play trapped-in-the-dollhouse.", accent: "#8b5cf6" },
    { slug: "tds-tower-destiny-survive", title: "tds-tower-destiny-survive", rule_text: "Play tds-tower-destiny-survive.", accent: "#8b5cf6" },
    { slug: "fight-and-loot", title: "fight-and-loot", rule_text: "Play fight-and-loot.", accent: "#8b5cf6" },
    { slug: "sea-of-sharks", title: "sea-of-sharks", rule_text: "Play sea-of-sharks.", accent: "#8b5cf6" },
    { slug: "clash-of-cards", title: "clash-of-cards", rule_text: "Play clash-of-cards.", accent: "#8b5cf6" },
    { slug: "oozys-lab", title: "oozys-lab", rule_text: "Play oozys-lab.", accent: "#8b5cf6" },
    { slug: "dan-the-man", title: "dan-the-man", rule_text: "Play dan-the-man.", accent: "#8b5cf6" },
    { slug: "samurai-sam", title: "samurai-sam", rule_text: "Play samurai-sam.", accent: "#8b5cf6" },
    { slug: "punch-master", title: "punch-master", rule_text: "Play punch-master.", accent: "#8b5cf6" },
    { slug: "soccer-5", title: "soccer-5", rule_text: "Play soccer-5.", accent: "#8b5cf6" },
    { slug: "hero-vs-criminal", title: "hero-vs-criminal", rule_text: "Play hero-vs-criminal.", accent: "#8b5cf6" },
    { slug: "brain-test-5", title: "brain-test-5", rule_text: "Play brain-test-5.", accent: "#8b5cf6" },
    { slug: "numbers-match", title: "numbers-match", rule_text: "Play numbers-match.", accent: "#8b5cf6" },
    { slug: "superweird", title: "superweird", rule_text: "Play superweird.", accent: "#8b5cf6" },
    { slug: "moto-trap", title: "moto-trap", rule_text: "Play moto-trap.", accent: "#8b5cf6" },
    { slug: "car-circle", title: "car-circle", rule_text: "Play car-circle.", accent: "#8b5cf6" },
    { slug: "ball-vs-block", title: "ball-vs-block", rule_text: "Play ball-vs-block.", accent: "#8b5cf6" },
    { slug: "home-builder-clicker", title: "home-builder-clicker", rule_text: "Play home-builder-clicker.", accent: "#8b5cf6" },
    { slug: "sea-catcher", title: "sea-catcher", rule_text: "Play sea-catcher.", accent: "#8b5cf6" },
    { slug: "kitten-out", title: "kitten-out", rule_text: "Play kitten-out.", accent: "#8b5cf6" },
    { slug: "marina-club-rush", title: "marina-club-rush", rule_text: "Play marina-club-rush.", accent: "#8b5cf6" },
    { slug: "airplane-manager", title: "airplane-manager", rule_text: "Play airplane-manager.", accent: "#8b5cf6" },
    { slug: "gunforce", title: "gunforce", rule_text: "Play gunforce.", accent: "#8b5cf6" },
    { slug: "spacebar-clicker", title: "spacebar-clicker", rule_text: "Play spacebar-clicker.", accent: "#8b5cf6" },
    { slug: "veggie-merge", title: "veggie-merge", rule_text: "Play veggie-merge.", accent: "#8b5cf6" },
    { slug: "a-small-world-cup-2", title: "a-small-world-cup-2", rule_text: "Play a-small-world-cup-2.", accent: "#8b5cf6" },
    { slug: "tens", title: "tens", rule_text: "Play tens.", accent: "#8b5cf6" },
    { slug: "lafufu-blind-box-dress-up", title: "lafufu-blind-box-dress-up", rule_text: "Play lafufu-blind-box-dress-up.", accent: "#8b5cf6" },
    { slug: "find-it", title: "find-it", rule_text: "Play find-it.", accent: "#8b5cf6" },
    { slug: "sushi-situation", title: "sushi-situation", rule_text: "Play sushi-situation.", accent: "#8b5cf6" },
    { slug: "draft-wars", title: "draft-wars", rule_text: "Play draft-wars.", accent: "#8b5cf6" },
    { slug: "annoying-teacher-punch-game", title: "annoying-teacher-punch-game", rule_text: "Play annoying-teacher-punch-game.", accent: "#8b5cf6" },
    { slug: "battle-blast", title: "battle-blast-1.1.0-rc1", rule_text: "Play battle-blast-1.1.0-rc1.", accent: "#8b5cf6" },
    { slug: "catch-a-pet", title: "Catch a Pet v1.0.3", rule_text: "Play Catch a Pet v1.0.3.", accent: "#8b5cf6" },
    { slug: "hide-and-paint", title: "Hide and paint - v62", rule_text: "Play Hide and paint - v62.", accent: "#8b5cf6" },
    { slug: "make-brainrots-online", title: "Make Brainrots Online", rule_text: "Play Make Brainrots Online.", accent: "#8b5cf6" },
    { slug: "monkey-tag-io", title: "Monkey Tag Arena", rule_text: "Play Monkey Tag Arena.", accent: "#8b5cf6" },
    { slug: "stickers-merge", title: "HTML5 Game", rule_text: "Play HTML5 Game.", accent: "#8b5cf6" },
    { slug: "tiger-tank-2", title: "Tiger Tank 2", rule_text: "Play Tiger Tank 2.", accent: "#8b5cf6" },
    { slug: "duck-merge", title: "duck-merge", rule_text: "Play duck-merge.", accent: "#8b5cf6" },
    { slug: "blumgi-splash", title: "blumgi-splash", rule_text: "Play blumgi-splash.", accent: "#8b5cf6" },
    { slug: "school-cleaning", title: "school-cleaning", rule_text: "Play school-cleaning.", accent: "#8b5cf6" },
    { slug: "talking-tom-gold-run", title: "TTGR_Live_1.0.0", rule_text: "Play TTGR_Live_1.0.0.", accent: "#8b5cf6" },
    { slug: "cozyville-find-hidden-objects", title: "cozyville-find-hidden-objects", rule_text: "Play cozyville-find-hidden-objects.", accent: "#8b5cf6" },
    { slug: "stunt-protocol-two-players", title: "stunt-protocol-two-players", rule_text: "Play stunt-protocol-two-players.", accent: "#8b5cf6" },
    { slug: "guns-guns-guns", title: "guns-guns-guns", rule_text: "Play guns-guns-guns.", accent: "#8b5cf6" },
    { slug: "world-of-yarn", title: "world-of-yarn", rule_text: "Play world-of-yarn.", accent: "#8b5cf6" },
    { slug: "bunny-miner", title: "bunny-miner", rule_text: "Play bunny-miner.", accent: "#8b5cf6" },
    { slug: "goal-gang", title: "goal-gang", rule_text: "Play goal-gang.", accent: "#8b5cf6" },
    { slug: "bubble-tower", title: "bubble-tower", rule_text: "Play bubble-tower.", accent: "#8b5cf6" },
    { slug: "snacky-snake", title: "snacky-snake", rule_text: "Play snacky-snake.", accent: "#8b5cf6" },
    { slug: "zombit", title: "zombit", rule_text: "Play zombit.", accent: "#8b5cf6" },
    { slug: "wheel-master", title: "wheel-master", rule_text: "Play wheel-master.", accent: "#8b5cf6" },
    { slug: "satisbox-builder", title: "satisbox-builder", rule_text: "Play satisbox-builder.", accent: "#8b5cf6" },
    { slug: "carnado-bike-stunt", title: "CARNADO BIKE STUNT", rule_text: "Play CARNADO BIKE STUNT.", accent: "#8b5cf6" },
    { slug: "blast-buddies", title: "blast-buddies", rule_text: "Play blast-buddies.", accent: "#8b5cf6" },
    { slug: "count-war", title: "count-war", rule_text: "Play count-war.", accent: "#8b5cf6" },
    { slug: "lips-diy-master", title: "Lips", rule_text: "Play Lips.", accent: "#8b5cf6" },
    { slug: "going-up-rooftop", title: "going-up-rooftop", rule_text: "Play going-up-rooftop.", accent: "#8b5cf6" },
    { slug: "lips-diy-master", title: "lips-diy-master", rule_text: "Play lips-diy-master.", accent: "#8b5cf6" },
    { slug: "keyboard-warrior", title: "keyboard-warrior", rule_text: "Play keyboard-warrior.", accent: "#8b5cf6" },
    { slug: "adventure-miner", title: "adventure-miner", rule_text: "Play adventure-miner.", accent: "#8b5cf6" },
    { slug: "dino-fighter", title: "dino-fighter", rule_text: "Play dino-fighter.", accent: "#8b5cf6" },
    { slug: "cleanup-crew", title: "cleanup-crew", rule_text: "Play cleanup-crew.", accent: "#8b5cf6" },
    { slug: "basketball-real", title: "basketball-real", rule_text: "Play basketball-real.", accent: "#8b5cf6" },
    { slug: "crazy-merge", title: "crazy-merge", rule_text: "Play crazy-merge.", accent: "#8b5cf6" },
    { slug: "jelly-sokoban", title: "jelly-sokoban", rule_text: "Play jelly-sokoban.", accent: "#8b5cf6" },
    { slug: "soccer-skills-2-world-cup", title: "soccer-skills-2-world-cup", rule_text: "Play soccer-skills-2-world-cup.", accent: "#8b5cf6" },
    { slug: "kpop-concert-dress-up", title: "kpop-concert-dress-up", rule_text: "Play kpop-concert-dress-up.", accent: "#8b5cf6" },
    { slug: "drift-hunters", title: "drift-hunters", rule_text: "Play drift-hunters.", accent: "#8b5cf6" },
    { slug: "knockout-penguins", title: "knockout-penguins", rule_text: "Play knockout-penguins.", accent: "#8b5cf6" },
    { slug: "decor-life", title: "decor-life", rule_text: "Play decor-life.", accent: "#8b5cf6" },
    { slug: "janes-fashion-studio", title: "janes-fashion-studio", rule_text: "Play janes-fashion-studio.", accent: "#8b5cf6" },
    { slug: "real-city-bikes", title: "real-city-bikes", rule_text: "Play real-city-bikes.", accent: "#8b5cf6" },
    { slug: "sort-the-court", title: "sort-the-court", rule_text: "Play sort-the-court.", accent: "#8b5cf6" },
    { slug: "skill-knight", title: "skill-knight", rule_text: "Play skill-knight.", accent: "#8b5cf6" },
    { slug: "jelly-fruit-merge", title: "jelly-fruit-merge", rule_text: "Play jelly-fruit-merge.", accent: "#8b5cf6" },
    { slug: "wreck-the-robot", title: "wreck-the-robot", rule_text: "Play wreck-the-robot.", accent: "#8b5cf6" },
    { slug: "freaky-clown-town-mystery", title: "freaky-clown-town-mystery", rule_text: "Play freaky-clown-town-mystery.", accent: "#8b5cf6" },
    { slug: "magic-battleground", title: "magic-battleground", rule_text: "Play magic-battleground.", accent: "#8b5cf6" },
    { slug: "free-skate", title: "free-skate", rule_text: "Play free-skate.", accent: "#8b5cf6" },
    { slug: "alien-raid-monster-evolution", title: "alien-raid-monster-evolution", rule_text: "Play alien-raid-monster-evolution.", accent: "#8b5cf6" },
    { slug: "tuning-car-racing", title: "tuning-car-racing", rule_text: "Play tuning-car-racing.", accent: "#8b5cf6" },
    { slug: "metamon", title: "metamon", rule_text: "Play metamon.", accent: "#8b5cf6" },
    { slug: "crazy-race", title: "crazy-race", rule_text: "Play crazy-race.", accent: "#8b5cf6" },
    { slug: "diva-makeup-studio", title: "diva-makeup-studio", rule_text: "Play diva-makeup-studio.", accent: "#8b5cf6" },
    { slug: "flat-baseball", title: "flat-baseball", rule_text: "Play flat-baseball.", accent: "#8b5cf6" },
    { slug: "cat-simulator", title: "cat-simulator", rule_text: "Play cat-simulator.", accent: "#8b5cf6" },
    { slug: "fashion-legends", title: "fashion-legends", rule_text: "Play fashion-legends.", accent: "#8b5cf6" },
    { slug: "mine-and-dig", title: "mine-and-dig", rule_text: "Play mine-and-dig.", accent: "#8b5cf6" },
    { slug: "tank-stars", title: "tank-stars", rule_text: "Play tank-stars.", accent: "#8b5cf6" },
    { slug: "4th-and-goal-2026", title: "4th-and-goal-2026", rule_text: "Play 4th-and-goal-2026.", accent: "#8b5cf6" },
    { slug: "punchy-guy", title: "punchy-guy", rule_text: "Play punchy-guy.", accent: "#8b5cf6" },
    { slug: "you-monster", title: "you-monster", rule_text: "Play you-monster.", accent: "#8b5cf6" },
    { slug: "push-titans", title: "push-titans", rule_text: "Play push-titans.", accent: "#8b5cf6" },
    { slug: "neon-challenge-legends", title: "neon-challenge-legends", rule_text: "Play neon-challenge-legends.", accent: "#8b5cf6" },
    { slug: "ludo-king", title: "ludo-king", rule_text: "Play ludo-king.", accent: "#8b5cf6" },
    { slug: "idle-spinner-factory-builder", title: "idle-spinner-factory-builder", rule_text: "Play idle-spinner-factory-builder.", accent: "#8b5cf6" },
    { slug: "gas-station", title: "gas-station", rule_text: "Play gas-station.", accent: "#8b5cf6" },
    { slug: "grass-knight", title: "grass-knight", rule_text: "Play grass-knight.", accent: "#8b5cf6" },
    { slug: "slime-dunk", title: "slime-dunk", rule_text: "Play slime-dunk.", accent: "#8b5cf6" },
    { slug: "the-superhero-league-2", title: "the-superhero-league-2", rule_text: "Play the-superhero-league-2.", accent: "#8b5cf6" },
    { slug: "sword-road", title: "sword-road", rule_text: "Play sword-road.", accent: "#8b5cf6" },
    { slug: "carrom-multiplayer", title: "carrom-multiplayer", rule_text: "Play carrom-multiplayer.", accent: "#8b5cf6" },
    { slug: "turnament", title: "turnament", rule_text: "Play turnament.", accent: "#8b5cf6" },
    { slug: "papa-louie-3", title: "papa-louie-3", rule_text: "Play papa-louie-3.", accent: "#8b5cf6" },
    { slug: "mirror-image", title: "mirror-image", rule_text: "Play mirror-image.", accent: "#8b5cf6" },
    { slug: "bos-bedroom", title: "bos-bedroom", rule_text: "Play bos-bedroom.", accent: "#8b5cf6" },
    { slug: "bubble-heroes", title: "bubble-heroes", rule_text: "Play bubble-heroes.", accent: "#8b5cf6" },
    { slug: "racing-rampage", title: "racing-rampage", rule_text: "Play racing-rampage.", accent: "#8b5cf6" },
    { slug: "snek-left", title: "snek-left", rule_text: "Play snek-left.", accent: "#8b5cf6" },
    { slug: "snow-riders", title: "snow-riders", rule_text: "Play snow-riders.", accent: "#8b5cf6" },
    { slug: "papa-louie-2", title: "papa-louie-2", rule_text: "Play papa-louie-2.", accent: "#8b5cf6" },
    { slug: "whip-flip", title: "whip-flip", rule_text: "Play whip-flip.", accent: "#8b5cf6" },
    { slug: "human-bullet-gun", title: "human-bullet-gun", rule_text: "Play human-bullet-gun.", accent: "#8b5cf6" },
    { slug: "graveyard-shift", title: "graveyard-shift", rule_text: "Play graveyard-shift.", accent: "#8b5cf6" },
    { slug: "speed-stars", title: "speed-stars", rule_text: "Play speed-stars.", accent: "#8b5cf6" },
    { slug: "brain-test-special", title: "brain-test-special", rule_text: "Play brain-test-special.", accent: "#8b5cf6" },
    { slug: "cat-bird", title: "cat-bird", rule_text: "Play cat-bird.", accent: "#8b5cf6" },
    { slug: "pizza-planet", title: "pizza-planet", rule_text: "Play pizza-planet.", accent: "#8b5cf6" },
    { slug: "eggsplosion", title: "eggsplosion", rule_text: "Play eggsplosion.", accent: "#8b5cf6" },
    { slug: "planet-destruction", title: "planet-destruction", rule_text: "Play planet-destruction.", accent: "#8b5cf6" },
    { slug: "tear-blocks-down", title: "tear-blocks-down", rule_text: "Play tear-blocks-down.", accent: "#8b5cf6" },
    { slug: "little-tricky-prankster", title: "little-tricky-prankster", rule_text: "Play little-tricky-prankster.", accent: "#8b5cf6" },
    { slug: "no-pain-no-gain", title: "no-pain-no-gain", rule_text: "Play no-pain-no-gain.", accent: "#8b5cf6" },
    { slug: "cube-builder", title: "cube-builder", rule_text: "Play cube-builder.", accent: "#8b5cf6" },
    { slug: "elf-backpack", title: "elf-backpack", rule_text: "Play elf-backpack.", accent: "#8b5cf6" },
    { slug: "wonder-high-dressup", title: "wonder-high-dressup", rule_text: "Play wonder-high-dressup.", accent: "#8b5cf6" },
    { slug: "pizza-day", title: "pizza-day", rule_text: "Play pizza-day.", accent: "#8b5cf6" },
    { slug: "obby-roads", title: "obby-roads", rule_text: "Play obby-roads.", accent: "#8b5cf6" },
    { slug: "bacon-survivor", title: "bacon-survivor", rule_text: "Play bacon-survivor.", accent: "#8b5cf6" },
    { slug: "hill-climb-racing-lite", title: "hill-climb-racing-lite", rule_text: "Play hill-climb-racing-lite.", accent: "#8b5cf6" },
    { slug: "ludo-online", title: "ludo-online", rule_text: "Play ludo-online.", accent: "#8b5cf6" },
    { slug: "blumgi-bounce", title: "blumgi-bounce", rule_text: "Play blumgi-bounce.", accent: "#8b5cf6" },
    { slug: "ragdoll-drop", title: "ragdoll-drop", rule_text: "Play ragdoll-drop.", accent: "#8b5cf6" },
    { slug: "kates-cooking-party", title: "kates-cooking-party", rule_text: "Play kates-cooking-party.", accent: "#8b5cf6" },
    { slug: "dino-quake", title: "dino-quake", rule_text: "Play dino-quake.", accent: "#8b5cf6" },
    { slug: "beardie-craft-survival", title: "beardie-craft-survival", rule_text: "Play beardie-craft-survival.", accent: "#8b5cf6" },
    { slug: "pro-shooter", title: "pro-shooter", rule_text: "Play pro-shooter.", accent: "#8b5cf6" },
    { slug: "my-city-horse-stable", title: "my-city-horse-stable", rule_text: "Play my-city-horse-stable.", accent: "#8b5cf6" },
    { slug: "party-time", title: "party-time", rule_text: "Play party-time.", accent: "#8b5cf6" },
    { slug: "world-of-screw", title: "world-of-screw", rule_text: "Play world-of-screw.", accent: "#8b5cf6" },
    { slug: "royal-flush-merge", title: "royal-flush-merge", rule_text: "Play royal-flush-merge.", accent: "#8b5cf6" },
    { slug: "monster-max", title: "monster-max", rule_text: "Play monster-max.", accent: "#8b5cf6" },
    { slug: "life-choices-2-life-simulator", title: "life-choices-2-life-simulator", rule_text: "Play life-choices-2-life-simulator.", accent: "#8b5cf6" },
    { slug: "nail-salon", title: "nail-salon", rule_text: "Play nail-salon.", accent: "#8b5cf6" },
    { slug: "subway-surfers-blast", title: "subway-surfers-blast", rule_text: "Play subway-surfers-blast.", accent: "#8b5cf6" },
    { slug: "subway-surfers-match", title: "subway-surfers-match", rule_text: "Play subway-surfers-match.", accent: "#8b5cf6" },
    { slug: "scary-teacher-playtime-adventure", title: "scary-teacher-playtime-adventure", rule_text: "Play scary-teacher-playtime-adventure.", accent: "#8b5cf6" },
    { slug: "sky-race", title: "sky-race", rule_text: "Play sky-race.", accent: "#8b5cf6" },
    { slug: "snake-vs-human", title: "snake-vs-human", rule_text: "Play snake-vs-human.", accent: "#8b5cf6" },
    { slug: "thung-wars", title: "thung-wars", rule_text: "Play thung-wars.", accent: "#8b5cf6" },
    { slug: "grass-cutter", title: "grass-cutter", rule_text: "Play grass-cutter.", accent: "#8b5cf6" },
    { slug: "color-merge-lines", title: "color-merge-lines", rule_text: "Play color-merge-lines.", accent: "#8b5cf6" },
    { slug: "roller", title: "roller", rule_text: "Play roller.", accent: "#8b5cf6" },
    { slug: "stickman-maze-run", title: "stickman-maze-run", rule_text: "Play stickman-maze-run.", accent: "#8b5cf6" },
    { slug: "dwerg", title: "dwerg", rule_text: "Play dwerg.", accent: "#8b5cf6" },
    { slug: "hockey-taka", title: "hockey-taka", rule_text: "Play hockey-taka.", accent: "#8b5cf6" },
    { slug: "pocket-car-city", title: "pocket-car-city", rule_text: "Play pocket-car-city.", accent: "#8b5cf6" },
    { slug: "the-third-piglets-tower", title: "the-third-piglets-tower", rule_text: "Play the-third-piglets-tower.", accent: "#8b5cf6" },
    { slug: "capitalist-bus-driver", title: "capitalist-bus-driver", rule_text: "Play capitalist-bus-driver.", accent: "#8b5cf6" },
    { slug: "stupidella-horror-2", title: "stupidella-horror-2", rule_text: "Play stupidella-horror-2.", accent: "#8b5cf6" },
    { slug: "merge-monster-battles", title: "merge-monster-battles", rule_text: "Play merge-monster-battles.", accent: "#8b5cf6" },
    { slug: "brainrot-merge", title: "brainrot-merge", rule_text: "Play brainrot-merge.", accent: "#8b5cf6" },
    { slug: "critters-quest", title: "critters-quest", rule_text: "Play critters-quest.", accent: "#8b5cf6" },
    { slug: "the-real-juggle", title: "the-real-juggle", rule_text: "Play the-real-juggle.", accent: "#8b5cf6" },
    { slug: "evolution-game", title: "evolution-game", rule_text: "Play evolution-game.", accent: "#8b5cf6" },
    { slug: "porki-poke", title: "porki-poke", rule_text: "Play porki-poke.", accent: "#8b5cf6" },
    { slug: "squid-dash", title: "squid-dash", rule_text: "Play squid-dash.", accent: "#8b5cf6" },
    { slug: "blocky-out", title: "blocky-out", rule_text: "Play blocky-out.", accent: "#8b5cf6" },
    { slug: "rumble-rush", title: "rumble-rush", rule_text: "Play rumble-rush.", accent: "#8b5cf6" },
    { slug: "beach-boxing-simulator", title: "beach-boxing-simulator", rule_text: "Play beach-boxing-simulator.", accent: "#8b5cf6" },
    { slug: "drills-merge-master", title: "drills-merge-master", rule_text: "Play drills-merge-master.", accent: "#8b5cf6" },
    { slug: "right-jump", title: "right-jump", rule_text: "Play right-jump.", accent: "#8b5cf6" },
    { slug: "i-am-hall-security", title: "i-am-hall-security", rule_text: "Play i-am-hall-security.", accent: "#8b5cf6" },
    { slug: "meme-madness", title: "meme-madness", rule_text: "Play meme-madness.", accent: "#8b5cf6" },
    { slug: "buck-bounce", title: "buck-bounce", rule_text: "Play buck-bounce.", accent: "#8b5cf6" },
    { slug: "kigurumi-dress-up", title: "kigurumi-dress-up", rule_text: "Play kigurumi-dress-up.", accent: "#8b5cf6" },
    { slug: "bee-sort-by-sam", title: "bee-sort-by-sam", rule_text: "Play bee-sort-by-sam.", accent: "#8b5cf6" },
    { slug: "cafe-bara", title: "cafe-bara", rule_text: "Play cafe-bara.", accent: "#8b5cf6" },
    { slug: "a-cleaning-story", title: "a-cleaning-story", rule_text: "Play a-cleaning-story.", accent: "#8b5cf6" },
    { slug: "cube-miner-escape-from-prison", title: "cube-miner-escape-from-prison", rule_text: "Play cube-miner-escape-from-prison.", accent: "#8b5cf6" },
    { slug: "the-superhero-league", title: "the-superhero-league", rule_text: "Play the-superhero-league.", accent: "#8b5cf6" },
    { slug: "snow-plow", title: "snow-plow", rule_text: "Play snow-plow.", accent: "#8b5cf6" },
    { slug: "morph-balls", title: "morph-balls", rule_text: "Play morph-balls.", accent: "#8b5cf6" },
    { slug: "block-sandbox", title: "block-sandbox", rule_text: "Play block-sandbox.", accent: "#8b5cf6" },
    { slug: "diva-hair-salon", title: "diva-hair-salon", rule_text: "Play diva-hair-salon.", accent: "#8b5cf6" },
    { slug: "screw-jam-puzzle", title: "screw-jam-puzzle", rule_text: "Play screw-jam-puzzle.", accent: "#8b5cf6" },
    { slug: "need-for-madness", title: "need-for-madness", rule_text: "Play need-for-madness.", accent: "#8b5cf6" },
    { slug: "pets-park", title: "pets-park", rule_text: "Play pets-park.", accent: "#8b5cf6" },
    { slug: "doodle-race", title: "doodle-race", rule_text: "Play doodle-race.", accent: "#8b5cf6" },
    { slug: "heroes-league", title: "heroes-league", rule_text: "Play heroes-league.", accent: "#8b5cf6" },
    { slug: "coin-machine", title: "coin-machine", rule_text: "Play coin-machine.", accent: "#8b5cf6" },
    { slug: "flying-wheels-evolution", title: "flying-wheels-evolution", rule_text: "Play flying-wheels-evolution.", accent: "#8b5cf6" },
    { slug: "crazy-descent", title: "crazy-descent", rule_text: "Play crazy-descent.", accent: "#8b5cf6" },
    { slug: "ant-art-tycoon", title: "ant-art-tycoon", rule_text: "Play ant-art-tycoon.", accent: "#8b5cf6" },
    { slug: "run-3", title: "run-3", rule_text: "Play run-3.", accent: "#8b5cf6" },
    { slug: "blockpost", title: "blockpost", rule_text: "Play blockpost.", accent: "#8b5cf6" },
    { slug: "blockpost-legacy", title: "blockpost-legacy", rule_text: "Play blockpost-legacy.", accent: "#8b5cf6" },
    { slug: "jetpack-fury", title: "jetpack-fury", rule_text: "Play jetpack-fury.", accent: "#8b5cf6" },
    { slug: "digger-escape", title: "digger-escape", rule_text: "Play digger-escape.", accent: "#8b5cf6" },
    { slug: "auto-ninja", title: "auto-ninja", rule_text: "Play auto-ninja.", accent: "#8b5cf6" },
    { slug: "moving-blocks", title: "moving-blocks", rule_text: "Play moving-blocks.", accent: "#8b5cf6" },
    { slug: "cougar-simulator-big-cats", title: "cougar-simulator-big-cats", rule_text: "Play cougar-simulator-big-cats.", accent: "#8b5cf6" },
    { slug: "schools-out-the-great-escape", title: "schools-out-the-great-escape", rule_text: "Play schools-out-the-great-escape.", accent: "#8b5cf6" },
    { slug: "basketball-superstars", title: "basketball-superstars", rule_text: "Play basketball-superstars.", accent: "#8b5cf6" },
    { slug: "gobattle2", title: "gobattle2", rule_text: "Play gobattle2.", accent: "#8b5cf6" },
    { slug: "samurai-punch", title: "samurai-punch", rule_text: "Play samurai-punch.", accent: "#8b5cf6" },
    { slug: "drift-boss", title: "Drift Boss", rule_text: "Play Drift Boss.", accent: "#8b5cf6" },
    { slug: "little-farm-world", title: "little-farm-world", rule_text: "Play little-farm-world.", accent: "#8b5cf6" },
    { slug: "moms-diary-cooking-games", title: "moms-diary-cooking-games", rule_text: "Play moms-diary-cooking-games.", accent: "#8b5cf6" },
    { slug: "scary-teacher-hide-seek-games", title: "scary-teacher-hide-seek-games", rule_text: "Play scary-teacher-hide-seek-games.", accent: "#8b5cf6" },
    { slug: "demolition-simulator", title: "demolition-simulator", rule_text: "Play demolition-simulator.", accent: "#8b5cf6" },
    { slug: "family-sort", title: "family-sort", rule_text: "Play family-sort.", accent: "#8b5cf6" },
    { slug: "kick-the-buddy", title: "kick-the-buddy", rule_text: "Play kick-the-buddy.", accent: "#8b5cf6" },
    { slug: "slime-keyboard-escape", title: "slime-keyboard-escape", rule_text: "Play slime-keyboard-escape.", accent: "#8b5cf6" },
    {
      slug: "drift-boss",
      title: "Drift Boss",
      rule_text: "Drift as far as you can without falling off.",
      accent: "#f59e0b",
    },
    {
      slug: "penalty-shooters-2",
      title: "Penalty Shooters 2",
      rule_text: "Beat the keeper. Win the cup.",
      accent: "#fbbf24",
    },
    {
      slug: "soccer-real",
      title: "Soccer REAL",
      rule_text: "Score more than the keeper can save.",
      accent: "#4ade80",
    },
    {
      slug: "master-chess",
      title: "Master Chess",
      rule_text: "Checkmate the master. Every move counts.",
      accent: "#a78bfa",
    },
    {
      slug: "basketball-stars",
      title: "Basketball Stars",
      rule_text: "Outscore the rival. Sink the buzzer-beater.",
      accent: "#fb923c",
    },
    {
      slug: "stickman-hook",
      title: "Stickman Hook",
      rule_text: "Swing through the course. Don't let go.",
      accent: "#f472b6",
    },
    {
      slug: "happy-glass",
      title: "Happy Glass",
      rule_text: "Draw the line. Fill the glass.",
      accent: "#38bdf8",
    },
    {
      slug: "drive-mad",
      title: "Drive Mad",
      rule_text: "Race the road. Flip the finish.",
      accent: "#22c55e",
    },
    {
      slug: "slice-master",
      title: "Slice Master",
      rule_text: "Slice every object. Miss nothing.",
      accent: "#ff8a00",
    },
    {
      slug: "level-devil",
      title: "Level Devil",
      rule_text: "Climb the tower. Every floor is out to get you.",
      accent: "#ef4444",
    },
    {
      slug: "game-2048",
      title: "2048",
      rule_text: "Swipe to merge tiles and reach 2048.",
      accent: "#edc22e",
    },
    {
      slug: "ping-pong-bugs",
      title: "Ping Pong Bugs",
      rule_text: "Smash every wave of bugs off the table before they land.",
      accent: "#d946ef",
    },
  ],
  likes: {},
  engagement: {},
  followedCreatorIds: [],
  stats: {
    rankedRuns: 0,
    rankedGames: 0,
    savedGames: 0,
    followingCreators: 0,
  },
  auth: { google: false, discord: false },
};
