import type { BootstrapData } from "./types";

export const OFFLINE_BOOTSTRAP: BootstrapData = {
  player: {
    id: "offline-practice",
    handle: "OFFLINE",
    avatarUrl: null,
    provider: "guest",
    isGuest: true,
  },
  games: [
    {
      slug: "pulse-lock",
      title: "Pulse Lock",
      rule_text: "Tap when the pulse hits the live zone.",
      accent: "#38b6ff",
    },
    {
      slug: "color-clash",
      title: "Color Clash",
      rule_text: "Tap the color named, not the color shown.",
      accent: "#b06cff",
    },
    {
      slug: "stack-shift",
      title: "Stack Shift",
      rule_text: "Tap to lock each moving block in place.",
      accent: "#21d4fd",
    },
    {
      slug: "memory-grid",
      title: "Memory Grid",
      rule_text: "Watch the signal. Repeat the growing pattern.",
      accent: "#ff4fd8",
    },
    {
      slug: "meteor-dodge",
      title: "Meteor Dodge",
      rule_text: "Drag sideways. Stay clear of every meteor.",
      accent: "#ff9f1c",
    },
    {
      slug: "subway-surfers",
      title: "Subway Surfers",
      rule_text: "Swipe to dodge trains, jump barriers, and chase the highest score.",
      accent: "#ffd32a",
    },
    {
      slug: "dino-runner",
      title: "Dino Runner",
      rule_text: "Tap to jump. Survive the endless desert.",
      accent: "#4ade80",
    },
    {
      slug: "arithmetica",
      title: "ArithmeticA",
      rule_text: "Solve the math. Beat the clock.",
      accent: "#f59e0b",
    },
    {
      slug: "67-game",
      title: "67 Game",
      rule_text: "Solve rapid-fire puzzle levels before the clock runs out.",
      accent: "#fe930e",
    },
    {
      slug: "archery-king",
      title: "Archery King",
      rule_text: "Draw, aim with the wind, and hit the target in 24 solo levels.",
      accent: "#ef4444",
    },
    {
      slug: "smash-room",
      title: "Smash Room",
      rule_text: "Choose a tool and smash every voxel object in sight.",
      accent: "#fb923c",
    },
    {
      slug: "temple-run-2-frozen-shadows",
      title: "Temple Run 2: Frozen Shadows",
      rule_text: "Run the frozen path. Swipe to turn, jump, and slide past every trap.",
      accent: "#b7e6ff",
    },
    {
      slug: "stickman-fury",
      title: "Stickman Fury",
      rule_text: "Move, jump, fight, and survive every physics-driven arena.",
      accent: "#ef4444",
      ranked: false,
    },
    {
      slug: "plonky",
      title: "Plonky",
      rule_text: "Run, jump, and outsmart the traps.",
      accent: "#1dd7d7",
    },
    {
      slug: "fruit-ninja",
      title: "Fruit Ninja",
      rule_text: "Swipe to slice fruit for points. Avoid the bombs.",
      accent: "#84cc16",
    },
    {
      slug: "count-control-legends",
      title: "Count Control Legends",
      rule_text: "Move left and right, grow your crew through the best number gates, and conquer the course.",
      accent: "#38bdf8",
    },
    {
      slug: "johnny-trigger-sniper",
      title: "Johnny Trigger - Sniper Game",
      rule_text: "Aim carefully, eliminate the targets, and protect civilians.",
      accent: "#00c565",
      ranked: false,
    },
    {
      slug: "rocket-soccer-derby",
      title: "Rocket Soccer Derby",
      rule_text: "Drive, boost, hit the ball, and score more goals than your opponent.",
      accent: "#ff7a47",
      ranked: false,
    },
    {
      slug: "dig-out-of-prison",
      title: "Dig out of Prison",
      rule_text: "Dig, gather resources, and escape the prison compound.",
      accent: "#7bcf63",
      ranked: false,
    },
    {
      slug: "theft-city",
      title: "Theft City",
      rule_text: "Explore the city, collect loot, escape danger, and build your criminal empire.",
      accent: "#facc15",
    },
    {
      slug: "city-cab-rush",
      title: "City Cab Rush",
      rule_text: "Drive through traffic, pick up fares, and race to the destination.",
      accent: "#fbbf24",
    },
    {
      slug: "supercar-legends",
      title: "Supercar Legends",
      rule_text: "Swipe left/right through math gates. Grow your run.",
      accent: "#ff3b6b",
    },
    {
      slug: "ping-pong-go",
      title: "Ping Pong Go",
      rule_text: "Swipe to serve and rally. Win every point against the CPU.",
      accent: "#06b6d4",
    },
    {
      slug: "tic-tac-toe",
      title: "Tic Tac Toe",
      rule_text: "Three in a row. Every game, every time.",
      accent: "#38bdf8",
    },
    {
      slug: "go-battle-2",
      title: "Go Battle 2",
      rule_text: "Win the arena. Battle for the top.",
      accent: "#f97316",
    },
    {
      slug: "stickman-battle",
      title: "Stickman Battle",
      rule_text: "Fight through the arena. Last one standing wins.",
      accent: "#ef4444",
    },
    {
      slug: "retro-bowl",
      title: "Retro Bowl",
      rule_text: "Lead your team to the championship.",
      accent: "#22c55e",
    },
    { slug: "domino", title: "domino", rule_text: "Play domino.", accent: "#8b5cf6" },
    { slug: "foosball", title: "foosball", rule_text: "Play foosball.", accent: "#8b5cf6" },
    { slug: "ludo-hero", title: "ludo-hero", rule_text: "Play ludo-hero.", accent: "#8b5cf6" },
    { slug: "moto-x3m", title: "moto-x3m", rule_text: "Play moto-x3m.", accent: "#8b5cf6" },
    { slug: "bubble-storm", title: "bubble-storm", rule_text: "Play bubble-storm.", accent: "#8b5cf6" },
    { slug: "spider-solitaire", title: "Spider Solitaire Plus", rule_text: "Play Spider Solitaire Plus.", accent: "#8b5cf6" },
    { slug: "master-checkers", title: "master-checkers", rule_text: "Play master-checkers.", accent: "#8b5cf6" },
    { slug: "four-in-a-row", title: "four-in-a-row", rule_text: "Play four-in-a-row.", accent: "#8b5cf6" },
    { slug: "monkey-mart", title: "MonkeyMart", rule_text: "Play MonkeyMart.", accent: "#8b5cf6" },
    { slug: "eggy-car", title: "Eggy Car", rule_text: "Play Eggy Car.", accent: "#8b5cf6" },
    { slug: "tiny-fishing", title: "Tiny Fishing by buyhtml5.com", rule_text: "Play Tiny Fishing by buyhtml5.com.", accent: "#8b5cf6" },
    { slug: "beauty-salon", title: "BeautySalon", rule_text: "Play BeautySalon.", accent: "#8b5cf6" },
    { slug: "fashion-fix-studio", title: "Fashion Fix Studio", rule_text: "Play Fashion Fix Studio.", accent: "#8b5cf6" },
    { slug: "phone-case-diy", title: "Case Coloring", rule_text: "Play Case Coloring.", accent: "#8b5cf6" },
    { slug: "clean-house", title: "Clean House - Poki", rule_text: "Play Clean House - Poki.", accent: "#8b5cf6" },
    { slug: "stunt-bike-extreme", title: "Stunt Bike Extreme - Poki", rule_text: "Play Stunt Bike Extreme - Poki.", accent: "#8b5cf6" },
    { slug: "idle-lumber-inc", title: "Idle Lumber Inc - Poki", rule_text: "Play Idle Lumber Inc - Poki.", accent: "#8b5cf6" },
    { slug: "my-perfect-hotel", title: "My Perfect Hotel - Poki", rule_text: "Play My Perfect Hotel - Poki.", accent: "#8b5cf6" },
    { slug: "snapstyle-dress-up", title: "SnapStyle Dress-up", rule_text: "Play SnapStyle Dress-up.", accent: "#8b5cf6" },
    { slug: "brain-test-tricky-puzzles", title: "Brain Test", rule_text: "Play Brain Test.", accent: "#8b5cf6" },
    { slug: "dragon-the-dragon", title: "Dragon the Dragon", rule_text: "Play Dragon the Dragon.", accent: "#8b5cf6" },
    { slug: "pet-mahjong-3d", title: "3D Mahjong", rule_text: "Play 3D Mahjong.", accent: "#8b5cf6" },
    { slug: "petnest-io", title: "Petnest.io", rule_text: "Play Petnest.io.", accent: "#8b5cf6" },
    { slug: "travel-merge", title: "Travel Merge 1.11.00", rule_text: "Play Travel Merge 1.11.00.", accent: "#8b5cf6" },
    { slug: "travel-merge", title: "travel-merge", rule_text: "Play travel-merge.", accent: "#8b5cf6" },
    { slug: "dragon-the-dragon", title: "dragon-the-dragon", rule_text: "Play dragon-the-dragon.", accent: "#8b5cf6" },
    { slug: "build-your-island", title: "build-your-island", rule_text: "Play build-your-island.", accent: "#8b5cf6" },
    { slug: "sandbox-of-elements", title: "sandbox-of-elements", rule_text: "Play sandbox-of-elements.", accent: "#8b5cf6" },
    { slug: "crowd-rush", title: "crowd-rush", rule_text: "Play crowd-rush.", accent: "#8b5cf6" },
    { slug: "harvest-loop", title: "harvest-loop", rule_text: "Play harvest-loop.", accent: "#8b5cf6" },
    { slug: "tiny-game-shop-tycoon", title: "tiny-game-shop-tycoon", rule_text: "Play tiny-game-shop-tycoon.", accent: "#8b5cf6" },
    { slug: "undead-slayer", title: "undead-slayer", rule_text: "Play undead-slayer.", accent: "#8b5cf6" },
    { slug: "knife-merge", title: "knife-merge", rule_text: "Play knife-merge.", accent: "#8b5cf6" },
    { slug: "family-life-simulator", title: "family-life-simulator", rule_text: "Play family-life-simulator.", accent: "#8b5cf6" },
    { slug: "dummies-fight", title: "dummies-fight", rule_text: "Play dummies-fight.", accent: "#8b5cf6" },
    { slug: "perfect-shape", title: "perfect-shape", rule_text: "Play perfect-shape.", accent: "#8b5cf6" },
    { slug: "flip-pounce", title: "flip-pounce", rule_text: "Play flip-pounce.", accent: "#8b5cf6" },
    { slug: "goalheads-io", title: "goalheads-io", rule_text: "Play goalheads-io.", accent: "#8b5cf6" },
    { slug: "goods-master", title: "goods-master", rule_text: "Play goods-master.", accent: "#8b5cf6" },
    { slug: "20f8", title: "20f8", rule_text: "Play 20f8.", accent: "#8b5cf6" },
    { slug: "fashion-dress-up-star", title: "fashion-dress-up-star", rule_text: "Play fashion-dress-up-star.", accent: "#8b5cf6" },
    { slug: "dino-simulator", title: "dino-simulator", rule_text: "Play dino-simulator.", accent: "#8b5cf6" },
    { slug: "bubbleshooter-x-basketball-3d", title: "bubbleshooter-x-basketball-3d", rule_text: "Play bubbleshooter-x-basketball-3d.", accent: "#8b5cf6" },
    { slug: "boomy-world", title: "boomy-world", rule_text: "Play boomy-world.", accent: "#8b5cf6" },
    { slug: "chick-flix", title: "chick-flix", rule_text: "Play chick-flix.", accent: "#8b5cf6" },
    { slug: "ball-guys", title: "ball-guys", rule_text: "Play ball-guys.", accent: "#8b5cf6" },
    { slug: "color-shapes", title: "Color Shapes", rule_text: "Play Color Shapes.", accent: "#8b5cf6" },
    { slug: "paperio-2", title: "Paper.io 2", rule_text: "Play Paper.io 2.", accent: "#8b5cf6" },
    { slug: "snow-yeet", title: "Snow Yeet", rule_text: "Play Snow Yeet.", accent: "#8b5cf6" },
    { slug: "robo-cleaner-simulator", title: "robo cleaner", rule_text: "Play robo cleaner.", accent: "#8b5cf6" },
    { slug: "noob-archer-2", title: "Noob Archer 2", rule_text: "Play Noob Archer 2.", accent: "#8b5cf6" },
    { slug: "carnado-boat-racing", title: "Carnado Boat Racing", rule_text: "Play Carnado Boat Racing.", accent: "#8b5cf6" },
    { slug: "super-dress", title: "SuperDress", rule_text: "Play SuperDress.", accent: "#8b5cf6" },
    { slug: "block-for-blood", title: "Block for Blood", rule_text: "Play Block for Blood.", accent: "#8b5cf6" },
    { slug: "dress-up-party", title: "dress-up-party", rule_text: "Play dress-up-party.", accent: "#8b5cf6" },
    { slug: "cuboy-adventure", title: "Cuboy", rule_text: "Play Cuboy.", accent: "#8b5cf6" },
    { slug: "cuboy-adventure", title: "cuboy-adventure", rule_text: "Play cuboy-adventure.", accent: "#8b5cf6" },
    { slug: "ragdoll-chaos", title: "ragdoll-chaos", rule_text: "Play ragdoll-chaos.", accent: "#8b5cf6" },
    { slug: "critter-chaos", title: "Squad CTF Prototype", rule_text: "Play Squad CTF Prototype.", accent: "#8b5cf6" },
    { slug: "happy-tidy-time", title: "Happy Tidy Time", rule_text: "Play Happy Tidy Time.", accent: "#8b5cf6" },
    { slug: "soccer-league", title: "soccer-league", rule_text: "Play soccer-league.", accent: "#8b5cf6" },
    { slug: "moto-trap", title: "biker", rule_text: "Play biker.", accent: "#8b5cf6" },
    { slug: "drift-boss", title: "Drift Boss", rule_text: "Play Drift Boss.", accent: "#8b5cf6" },
    { slug: "little-farm-world", title: "little-farm-world", rule_text: "Play little-farm-world.", accent: "#8b5cf6" },
    { slug: "moms-diary-cooking-games", title: "moms-diary-cooking-games", rule_text: "Play moms-diary-cooking-games.", accent: "#8b5cf6" },
    { slug: "scary-teacher-hide-seek-games", title: "scary-teacher-hide-seek-games", rule_text: "Play scary-teacher-hide-seek-games.", accent: "#8b5cf6" },
    { slug: "demolition-simulator", title: "demolition-simulator", rule_text: "Play demolition-simulator.", accent: "#8b5cf6" },
    { slug: "family-sort", title: "family-sort", rule_text: "Play family-sort.", accent: "#8b5cf6" },
    { slug: "kick-the-buddy", title: "kick-the-buddy", rule_text: "Play kick-the-buddy.", accent: "#8b5cf6" },
    { slug: "slime-keyboard-escape", title: "slime-keyboard-escape", rule_text: "Play slime-keyboard-escape.", accent: "#8b5cf6" },
    {
      slug: "drift-boss",
      title: "Drift Boss",
      rule_text: "Drift as far as you can without falling off.",
      accent: "#f59e0b",
    },
    {
      slug: "penalty-shooters-2",
      title: "Penalty Shooters 2",
      rule_text: "Beat the keeper. Win the cup.",
      accent: "#fbbf24",
    },
    {
      slug: "soccer-real",
      title: "Soccer REAL",
      rule_text: "Score more than the keeper can save.",
      accent: "#4ade80",
    },
    {
      slug: "master-chess",
      title: "Master Chess",
      rule_text: "Checkmate the master. Every move counts.",
      accent: "#a78bfa",
    },
    {
      slug: "basketball-stars",
      title: "Basketball Stars",
      rule_text: "Outscore the rival. Sink the buzzer-beater.",
      accent: "#fb923c",
    },
    {
      slug: "stickman-hook",
      title: "Stickman Hook",
      rule_text: "Swing through the course. Don't let go.",
      accent: "#f472b6",
    },
    {
      slug: "happy-glass",
      title: "Happy Glass",
      rule_text: "Draw the line. Fill the glass.",
      accent: "#38bdf8",
    },
    {
      slug: "drive-mad",
      title: "Drive Mad",
      rule_text: "Race the road. Flip the finish.",
      accent: "#22c55e",
    },
    {
      slug: "slice-master",
      title: "Slice Master",
      rule_text: "Slice every object. Miss nothing.",
      accent: "#ff8a00",
    },
    {
      slug: "level-devil",
      title: "Level Devil",
      rule_text: "Climb the tower. Every floor is out to get you.",
      accent: "#ef4444",
    },
    {
      slug: "game-2048",
      title: "2048",
      rule_text: "Swipe to merge tiles and reach 2048.",
      accent: "#edc22e",
    },
    {
      slug: "ping-pong-bugs",
      title: "Ping Pong Bugs",
      rule_text: "Smash every wave of bugs off the table before they land.",
      accent: "#d946ef",
    },
  ],
  likes: {},
  engagement: {},
  followedCreatorIds: [],
  stats: {
    rankedRuns: 0,
    rankedGames: 0,
    savedGames: 0,
    followingCreators: 0,
  },
  auth: { google: false, discord: false },
};
